### ISSUE TITLE
when passing query params, the routed URL removes '?' and has a single space. Not working with POST methods sending data in the request body. 404 error being thrown.

### ISSUE THREAD

**Issue by pathakravee** [ThreeMammals/Ocelot#1000]
## Expected Behavior / New Feature
1) /ApiGateway/person/GetPersonDetails?id=1 = > /Api/person/GetPersonDetails?id=1

## Actual Behavior / Motivation for New Feature
1) /ApiGateway/person/GetPersonDetails?id=1 = > /Api/person/GetPersonDetails id=1

## Steps to Reproduce the Problem

  1. configure reroute options with {catchAll} or {everything}
  2. have APIs POST methods with data or GET with query parameters
  3. open the gateway url and pass required params

## Specifications

  - Version: 13.5.2
  - Platform: Windows
  - Subsystem: IIS

**Comment by wast** [comment]
Please paste your ocelot ReRoute config.

**Comment by raman-m** [comment]
This is quite specific and it should be described in details!

@pathakravee Dear author!
We cannot reproduce your bug.

You have to provide and attach the following artifacts:
- config JSON aka routes in JSON aka **ocelot.json**
- app startup config in C#

My recommendation: Update to latest version!
And if the bug is still active, please reopen the issue. Thank you!
