### ISSUE TITLE
token exchange

### ISSUE THREAD

**Issue by ggoyal-Axum** [ThreeMammals/Ocelot#1007]
is there still no support for this feature?
https://github.com/ThreeMammals/Ocelot/issues/101

**Comment by ggoyal-Axum** [comment]
typo

**Comment by ggoyal-Axum** [comment]
I came across this solution which could be a promising option 
https://github.com/clawrenceks/ReferenceTokenExchange

**Comment by raman-m** [comment]
Which kind of advice do you need?
This is ancient issue!

----
> If token exchage is implemented at "PreAuthorisationMiddleware" step then it might work.

Sounds like a success story!

----
> I came across this solution which actually has the code to do token exchange
https://github.com/clawrenceks/ReferenceTokenExchange

I guess this solution is outdated because of .NET Core 2.0 version. I consider this repo as useless one now!
Identity Server 4 perfectly supports JWT because it is default auth scheme for IS4.
Also, Ocelot doesn't expose/forward a JWT token if you define authenticated route.
From the 2nd side, you can forward any tokens to downstream for anonymously defined routes.
