### ISSUE TITLE
Is it possible to request multiple downstreams in sequence ?

### ISSUE THREAD

**Issue by budi-wijaya-febetech-com** [ThreeMammals/Ocelot#1070]
## Expected Behavior / New Feature
I have 2 microservices : identity (A) and credit (B).
In the ocelot gateway, I need to call 2 api to both microservices above  (A and B) but in sequence, and pass the response data from 1st api call (A) as parameter to 2nd api call (B).

## Actual Behavior / Motivation for New Feature
is it possible to do as expected above? and How?

## Steps to Reproduce the Problem
In Ocelot Gateway:
1st sequence. call downstream A -> Response data id =13
2nd sequence. pass data id =13 to call downstream B/{id}

## Specifications

  - Version: Ocelot 13.8.0
  - Platform: ASP.NET Core 3 on Windows
  - Subsystem:

**Comment by slashersvk** [comment]
I am also looking for this feature.

**Comment by ctnkyrd** [comment]
this would be really nice if we can apprehend requests one after another

**Comment by sms7182** [comment]
i am also looking for this feature same as pipeline but with this solution , not working

**Comment by syedjalal12** [comment]
This feature was requested in 2019 and I'm still waiting for a response from the Ocelot team in 2023.

**Comment by niravmsoni** [comment]
Per https://github.com/ThreeMammals/Ocelot/issues/1207 - One of the suggestion is to have an API endpoint that takes in response from Microservice1 and uses the response when it makes call to Microservice2

**Comment by raman-m** [comment]
> Per #1207 - One of the suggestion is to have an API endpoint that takes in response from Microservice1 and uses the response when it makes call to Microservice2

@niravmsoni  You've got :yellow_square: yellow card!
Nerav, I am raising yellow card because of usage of cross issue comment as linker! :yellow_circle: 
But naturally your advice is clear.
I guess Mr(s). Budi Wijaya doesn't care! Ok, let's ask him (her)...

**Comment by raman-m** [comment]
@budi-wijaya-febetech-com 
Hi [Budi Wijaya](https://github.com/budi-wijaya-febetech-com)!

Is this issue still relevant as for you?  2019 - 2023, 5 years ago! Quite long story! :rofl: 
Ocelot has been released with [19.0.2](https://github.com/ThreeMammals/Ocelot/releases) version.
Would you like to check it? I believe [Aggregator](https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html) feature will help in most of cases.

Regarding your issue you've described 5 years ago about sequential calls.
> Is it possible to request multiple downstreams in sequence ?

Well... I am sure such functionality is outside of the responsibility of the gateway, because it is a natural feature of building sequential workflows. You have a client, you develop the client's workflow. Imagine you have 1st response of 1st request via gateway, then you're going to parse the response (not a responsibility of the gateway). After parsing 1st response you have some extracted data, and using programming language you need to start 2nd step of the workflow, making the 2nd request using extracted data as parameters... The same for the next steps in your workflow...

Another problem is that parsing logic will be a part of gateway's middleware. That is bad, because gateway load will be increased. So, it is a question who will perform parsing logic? Gateway? It is bad! Client? Yes, it is totally right!
So, gateway will run as workflow processor. That is incorrect on my opinion. But, the idea is interesting.

Finally, gateway cannot build and run sequential workflows making HTTP-requests. So, this is responsibility of the client of the gateway. But if some steps of your workflow are parallel then you could go with Aggregator feature of the gateway.

Hope it helps!

Your case is clear. The idea is interesting! But user scenario is still unclear and it has no good description.
So, requested functionality is very complex. It will take a lot of efforts to deliver such feature of workflow processor.

**Note**! This issue will be closed in a month, till June 1, 2023, in case of absent reply from you!

**Comment by raman-m** [comment]
@ThreeMammals/ocelot-core
@ThreeMammals/ocelot-owner 
Dear team,

Do we accept this issue?
Please, share your opinions!

**Comment by raman-m** [comment]
@raman-m  @philproctor  @margaale  @jps  @geffzhang  @briansantura  @binarymash  @anktsrkr  @abooraja 
Dear team,

Do we accept this issue?
Please, share your opinions!

**Comment by raman-m** [comment]
Dear @budi-wijaya-febetech-com 
You can look into the solution from issue [1207](1207#issuecomment-618348974) where you can find how to build custom aggregators on Ocelot's side.
I believe it is possible to implement some sequential aggregation. But you have to choose the main route for an aggregation. You have to implement parsers, extractors, data processing, data combining and control requests forwarding.

---
Hi Team!

This feature is not accepted by someone from the team. Also, I cannot accept it because it looks like a super-feature.
If someone will come to me with preliminary solution, and (s)he will be ready to help me then we can reopen the discussion.

Today this feature is going to be closed.
