### ISSUE TITLE
Retry calls to downstream

### ISSUE THREAD

**Issue by masterdimar** [ThreeMammals/Ocelot#1093]
Hi! 

Like Ocelot is already using Polly. Is there a way to retry X times the calls to downstream to prevent occasionally fails?

**Comment by suadev** [comment]
@TomPallister hi, 

I see "Retry policies" feature in the readme but I could not find it in docs. Any sample or explanation about it?

**Comment by arvindabes** [comment]
@suadev , @masterdimar Did you get any solution for above query? I need same behaviour .. need to retry downstream url in case of 503/408 error codes.

**Comment by raman-m** [comment]
We don't think that extending/adding Polly features in Ocelot core is a good idea.
We have a plans to remove Polly from Ocelot at all, because clients can apply Polly policies for requests to upstreams based on HTTP status of Ocelot upstream response.
Final decision is ongoing...

@RaynaldM  @ggnaegi 
FYI

**Comment by raman-m** [comment]
@masterdimar FYI
New version [23.2](https://github.com/ThreeMammals/Ocelot/milestone/5) will have extended feature: Polly resilience pipelines. Please use it. See PR #1914  
We believe you can implement any Polly pipeline you want.
