### ISSUE TITLE
Multiple routes, 2nd with no UpstreamHost causes a validation failure

### ISSUE THREAD

**Issue by seancarmichael** [ThreeMammals/Ocelot#1157]
## Expected Behavior / New Feature
Route should be correctly mapped

## Actual Behavior / Motivation for New Feature
Validation failure

## Steps to Reproduce the Problem

  1. Use this configuration:
```
"ReRoutes": [
        {
            "DownstreamPathTemplate": "/{everything}",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 5010
                }
            ],
            "UpstreamHost": "upstreamHost",
            "UpstreamPathTemplate": "/{everything}",
            "UpstreamHttpMethod": []
        },
        {
            "DownstreamPathTemplate": "/{everything}",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 5010
                }
            ],
            "UpstreamPathTemplate": "/{everything}",
            "UpstreamHttpMethod": []
        }
    ]
```
  
2. The mapping will work if specifying for the 2nd route:
           ` "UpstreamHost": ""`
 
## Specifications

  - Version: 14.0.5
  - Platform: Windows/Linux

**Comment by jlukawska** [comment]
Hello, 
I'm not sure why you're receiving 404 (any proxy in front of the Ocelot api?). Using the given example I'm receiving 500 (instead of 404) because of the configuration validation failure. The reason is that these two reRoutes are considered as duplicate when one of them has no UpstreamHost. I think I've found the problem and I'll create a PR with the fix.

Have you checked the logs if there is any error? To be sure that my solution will help you ;)

**Comment by seancarmichael** [comment]
Thanks @jlukawska.  I've update the description to refer to a validation failure.
