### ISSUE TITLE
Rate Limiting - allow limits per downstream route

### ISSUE THREAD

**Issue by ahofman** [ThreeMammals/Ocelot#1164]
##  New Feature

Add a new boolean configuration option to global rate limiting options called `counterPerDownStreamReRoute` . When set to true, call counts for rate limiting will be counted per down stream reroute, rather than per http verb/path.

## Actual Behavior / Motivation for New Feature

In the current implementation of rate limiting a counter is maintained for every unique combination of http verb and path used. This makes sense when paths are static - e.g., `GET /api/v1/foo` . 

However when paths contain parameters it starts to fall apart. For example if an endpoint allows creation of a resource and contains a UUID parameter: `POST /api/v1/foo/08AE6DCE-37F4-428B-B6B4-942B797D6D79` . In this case a client could trivially create many resources with different IDs and not be rate limited. 

The desired behaviour is to allow endpoints with path parameters to be effectively rate limited.

**Comment by MSchmack** [comment]
Encountered that behaviour when i tried to put a map tile server behind ocelot. 
The expected behaviour was to limit the entire downstreampath with the added rate limit options but the current behaviour seems to limit / count each and every route independently.

e.G. image of example routes used by a tile servers added for clarity
![image](https://user-images.githubusercontent.com/37783519/133599232-650d8630-cf15-4b7c-bc1f-e59055beb253.png)

**Comment by raman-m** [comment]
@ahofman
Limit your endpoint (Ocelot route) by `ClientId` aka **ClientIdHeader** option! Also you can limit connections by **ClientWhitelist**.
See: [Rate Limiting](https://ocelot.readthedocs.io/en/latest/features/ratelimiting.html)

Unfortunately we still don't limit by remote IP but we have some plans to implement this. See #1050
