### ISSUE TITLE
Rate limit enhancement 

### ISSUE THREAD

**Issue by sachinjagdale** [ThreeMammals/Ocelot#1226]
## Expected Behavior / New Feature
**Feature**: [Rate Limiting](../blob/develop/docs/features/ratelimiting.rst)

 [IRateLimitCounterHandler](/search?q=repo%3AThreeMammals%2FOcelot%20IRateLimitCounterHandler&type=code) contract should have async methods support.

## Actual Behavior / Motivation for New Feature

[IRateLimitCounterHandler](../blob/develop/src/Ocelot/RateLimit/IRateLimitCounterHandler.cs) currently having synchronous methods hence implementation has to be synchronous, hence we need to use cache provider synchronous methods only

Need to use custom middleware in code in order to support `async`. If Ocelot updates this interface then we can use this directly and boilerplate code can get removed.

# Steps to Reproduce the Problem
NA

## Specifications
NA

**Comment by sachinjagdale** [comment]
Can we update IRateLimitCounterHandler ? to return Task insted of void

**Comment by ks1990cn** [comment]
@sachinjagdale 
`ClientRateLimitMiddleware `is middleware provided, exactly what & why you need handler method to be asynchronous?
It has process request and locked so no instance should interfare while counting.
What kind of customization you are expecting?

**Comment by raman-m** [comment]
@sachinjagdale 
Thanks for the proposed issue!

---
> [IRateLimitCounterHandler](../blob/develop/src/Ocelot/RateLimit/IRateLimitCounterHandler.cs) currently having synchronous methods hence implementation has to be synchronous, hence we need to use cache provider synchronous methods only

Yes, it is! And, Yes, you have!

---
> Need to use custom middleware in code in order to support `async`. If Ocelot updates this interface then we can use this directly and boilerplate code can get removed.

In your forked repo you can change this interface and have some coding challenge to reimplement concrete classes.
But I don't see forked Ocelot repo! You [haven't forked Ocelot](/sachinjagdale?tab=repositories) at all!
And what "boilerplate code" are you talking about? You haven't forked the repo!

**Comment by raman-m** [comment]
> @sachinjagdale commented [on May 12, 2020](#issuecomment-627161073)
Can we update IRateLimitCounterHandler ? to return Task insted of void

In your forked repo you can develop whatever you want & wish! 😉 
But Ocelot team expects if you have a working solution you can return to us back with real PR to include your changes to Ocelot code base officially.

In my opinion, mentioned interface should have both versions: sync and async.
We cannot just remove sync versions at all because of breaking changes intro. So, that's why better to keep sync version and add async one.

**Are you still online?**
**Are you still with Ocelot?**
