### ISSUE TITLE
add prometheus metrics

### ISSUE THREAD

**Issue by EngRajabi** [ThreeMammals/Ocelot#1321]
## New Feature
prometheus metrics route

**Comment by raman-m** [comment]
Mohsen,
Will you personally contribute?
Do you have some really working proof of concepts aka  POC ?

@ggnaegi @RaynaldM  FYI

**Comment by EngRajabi** [comment]
> Mohsen, Will you personally contribute? Do you have some really working proof of concepts aka POC ?
> 
> @ggnaegi @RaynaldM FYI

Yes, I will send you the POC documents
I can add this feature to the project

**Comment by EngRajabi** [comment]
@raman-m 
In the world of distributed and large systems, it is necessary to have continuous monitoring of the system.
When ocelot is used, requests are input to the system. The required metrics should be produced for this point.
Metrics are divided into two categories. Internal metrics, for example, the amount of RAM or processor or the number of errors, which is so-called white-box monitoring.
External metrics such as user views of our services. which is so-called black-box monitoring.
Google article on this https://sre.google/sre-book/monitoring-distributed-systems/

**Comment by EngRajabi** [comment]
![image](https://github.com/ThreeMammals/Ocelot/assets/10164223/1aee47a9-0332-4d33-b81f-e68f35b7bda6)
![image](https://github.com/ThreeMammals/Ocelot/assets/10164223/71a800a7-377a-4b8d-a323-a40d87d49479)

**Comment by RaynaldM** [comment]
On our side, we are working on implement OpenTelemetry to Ocelot

**Comment by raman-m** [comment]
@RaynaldM Well... We have this [OpenTracing Status](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/features/tracing.rst#opentracing-status) paragraph in [Tracing](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/features/tracing.rst) docs.
It could be your area of responsibility. 😉 
Keep me updated on the plans of your dev team to move ahead and start migrations! 🆗 ❔ 
My plans understanding here
- We update Tracing to use latest package for [OpenTracing](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/features/tracing.rst#-opentracing) feature, release it. The package should be still available
- Deliver some POC or first version of new package for [OpenTelemetry](https://opentelemetry.io/) service. You can play major roles in delivering.

But this issue is about Prometheus service, and we don't have a package for it...

**Comment by raman-m** [comment]
@EngRajabi commented [on Mar 27](https://github.com/ThreeMammals/Ocelot/issues/1321#issuecomment-2022735008):

> Yes, I will send you the POC documents

Great! Will it be public repo on GitHub, I hope?
So, I need to clone it, build and run... and see some interesting charts 😄 

------
> I can add this feature to the project

So high confidence 🤣 I like it! 👍

**Comment by raman-m** [comment]
Dear @EngRajabi,
### You have the right to reopen this issue in the future if you come with a PR ready
