### ISSUE TITLE
Issue with OData context and nextLink urls behind gateway

### ISSUE THREAD

**Issue by codegolem** [ThreeMammals/Ocelot#1430]
I'm trying to use OData APIs behind an Ocelot gateway.
For example:

{
"DownstreamPathTemplate": "/odata/{everything}",
"UpstreamPathTemplate": "/reports/odata/v1/{everything}"
}

In this scenario, the OData APIs use the internal host and path in all metadata urls (like @odata.context and @odata.nextLink).

ex: {"@odata.context":"http://internal.host.name/reports/odata/v1/$metadata", ... }

I could customize those urls by code, but the OData service host doesn't know anything about the public url through which it was published.

Is there any way to forward the original url from the gateway to the underlying service? (maybe through headers?)
Or maybe transform the urls in the response body through custom functions?

Any suggestion on how to make OData work through the gateway?

Thank you!

**Comment by gyula-uszkai** [comment]
See if this helps https://github.com/OData/odata.net/issues/1694

**Comment by codegolem** [comment]
Hi @gyula-uszkai ,

thank you for your answer. I had already read that post: this is actually how I would expect to customize the urls by code in my OData implementation.

However, what I'm missing is how to retrieve the original (public) request url from the Ocelot gateway.
I was looking for some header that could be added to the upstream request, but I didn't find anything useful.

The only value I was able to forward through a **UpstreamHeaderTransform** was the **{BaseUrl}**, but this is a fixed configuration value.
I would have expected I could use a placeholder like **_{DownstreamPath}_** to forward the entire original url in a custom template or something like that.
I also tries to use the **UpstreamHeaderTransform** to add a custom header with the following value "**{BaseUrl}/odata/{everything}**", only to find out that placeholders are not handled as expected in the header tranform values (the header was created with that exact string value, placeholders not replaced).

By now I'm avoiding to use an Ocelot gateway in front of the OData APIs, but I think this is a great limitation.

Any additional advises are greatly appreciated.

**Comment by raman-m** [comment]
Hello @codegolem !
The problem was that OData filters cannot be routed by Ocelot as query strings.
This problem is fixed by #1182 
See commit https://github.com/ThreeMammals/Ocelot/commit/ae43f32fe32b322487623e4b1a22299c3d91bb73
To route all OData filtering URLs to downstream service you have to define special route by [Catch All Query String](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all-query-string) feature.
So, instead of `{BaseUrl}/odata/{everything}` you need to define `{BaseUrl}/odata/?{everything}`

Please, upgrade to the latest version and let us know your testing results!
Going to close the issue...
