### ISSUE TITLE
Service Discovery 

### ISSUE THREAD

**Issue by rubenmonteiro** [ThreeMammals/Ocelot#1439]
Hi all.
I have a simple question.
Is it possible to redirect a request from one endpoint to another is case of error or failure?
Example:
I have enpoint A1 and B1
A1 with route http://192.168.10.1/api/request
B1 with route http://192.168.10.2/api/request
Using service discovery or mapping the routes in the ocelot.json is it possible if the request to A1 fails make the send request to B1 before sending back the response.
I don't know if I made my self care with my doubt?
Thanks

**Comment by raman-m** [comment]
Hi Ruben!
Thanks for your interest in Ocelot!

I believe it is possible with current [Routing](https://ocelot.readthedocs.io/en/latest/features/routing.html) feature. You have to specify multiple "**DownstreamHostAndPorts**" objects in the array.
Finally, I need to check the code to prove that assumption...
But if ""DownstreamPathTemplate"" props varies then it is impossible, I guess.

Anyway, your question can be converted to feature request... Let's discuss!

**Comment by rubenmonteiro** [comment]
Hi @raman-m 
I didn't even remember that I had posted this :)

**Comment by raman-m** [comment]
@rubenmonteiro 
Can we close the issue?
Have I answered your question?

**Comment by raman-m** [comment]
@rubenmonteiro 
>Using service discovery or mapping the routes in the ocelot.json is it possible if the request to A1 fails make the send request to B1 before sending back the response.

Finally, I've got what you meant...
It looks like you want to build a sequential workflow...
So, Ocelot has no features for creation of  workflows on Ocelot's side. It is very difficult because workflow can contain complex conditions and unpredictable flows which will be hard to implement.
But... A lot of people is asking about workflows. The problem and design challenge here is... the location of definition and implementation.
My recommendation and there are 2 possible designs are 👉 
- Use Ocelot. Seems you need to use [Delegating Handlers](https://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html). The handler should be attached to the first step of the workflow. So, some route plays the role of the first step request. But response to upstream should be returned from the last step of workflow. In your case **A1** is the first step, and **B1** is the last step.
- Use clint's side. You are free to implement everything.

I'm afraid that usage of Service Discovery and workflows simultaneously will be not good idea. In theory it is possible. But our service discovery providers are not suitable to workflows.
Finally, I'd  say it is crazy idea.
If you have intention to have some coding challenge here which we can wrap into a PR then let me know.
