### ISSUE TITLE
What is the status of this project? 

### ISSUE THREAD

**Issue by wayne-o** [ThreeMammals/Ocelot#1457]
It seems that there are a few valid PRs that have been left to mothball and there hasn't been a release in over a year. 

I really like this project and don't consider there to be a real alternative project.

Microsoft featured it a lot in their examples of BFF - eg: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot

What is the status of this project? Is it dying or are there plans to maintain and improve it? 

I'm asking as someone who finds great value in this awesome piece of work, I'm also happy to offer some time if that's feasible / wanted.

w

**Comment by Hokutosei** [comment]
also using in production.. what's the status?

**Comment by knight1219** [comment]
I'm about to recommend we use for a massive project at work over something
like Azure API Management because it's something Microsoft has advertised
in their docs. I'm following this because if this project is currently
supported/abandoned I'll need to make some other options available for my
higher ups.

**Comment by wayne-o** [comment]
https://blog.duendesoftware.com/posts/20210326_bff/

**Comment by PatGet** [comment]
FYI:
https://twitter.com/ThreeMammals/status/1404477172341948421

**Comment by ThumbGen** [comment]
So, can we consider the project dead? I guess it's too dangerous to include it in a new business product :(

**Comment by qrider** [comment]
Hi, just wanted to follow up on this comment. Is this still maintained? Can someone add something to the readme if it isn't? 
Any recommendations on another open source API gateway? Looking for something better than Google Cloud's  API Gateway.
Thanks!!

**Comment by ggnaegi** [comment]
@raman-m Maybe you could answer there and close the issue?

**Comment by ks1990cn** [comment]
Still lot of open issues are pending - continous maintenance is going on. Recent migration to .Net 7 is done, so its upto date. New feature requests are also pending in issue section in which we can contribute. We can read more and suggest more features to this open project. I think open source projects never gets dead! 

If my answer makes sence we can close this issue.

@raman-m @ggnaegi

**Comment by raman-m** [comment]
> @ggnaegi commented [on Oct 2, 2023](#issuecomment-1743542808)

A-ha-ha! 🤣 Right! Thanks notifying me!

**Comment by raman-m** [comment]
>@ThumbGen commented [on Sep 7, 2021](#issuecomment-913860897)

Project is online since April this year. But active development phase has started in September.
And now we have a new [20.0.0](../releases) release

**Comment by raman-m** [comment]
>@qrider commented [on Jan 7, 2022](#issuecomment-1006999454)

Hi Quentin! It is maintained since April 2023. We have 2 releases this year. But sure, unfortunately we had an ugly On Hold status for last 3 years. Because of that we have a lot of problems in the project now.

We don't care about other API gateways. They are mostly products coming from enterprises. If you have a lot of money, and if you are OK to share personal and corp data of your clients to well-known corporations, then you could pay for the mentioned gateway by you.

**Comment by raman-m** [comment]
> @wayne-o commented [on Mar 26, 2021](#issue-841946931)

Hello Wayne!

> What is the status of this project?

Answering your question... It is online since April/May this year. During summer all PRs were reviewed.
During September we have prepared for the new release by adding some nice features and fixing bugs. See [Release Notes](https://github.com/ThreeMammals/Ocelot/releases) please! 
Hope you will return back to us with some nice & solid PRs! 😉 

Going to close this question...
