### ISSUE TITLE
Notice: End of support for ADAL

### ISSUE THREAD

**Issue by ShannonCanTech** [ThreeMammals/Ocelot#1489]
## Expected Behavior / New Feature
Migrate to MSAL

## Actual Behavior / Motivation for New Feature
Currently using soon-to-be deprecated SDK

## Hello from the Microsoft Authentication team!

On June 22, 2020, [we announced the end of support for Azure Active Directory Authentication Library (ADAL)](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363) and urged app owners to begin migrating over to [Microsoft Authentication Library (MSAL)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Fdevelop%2Fmsal-overview%23languages-and-frameworks&data=04%7C01%7CShannon.Foster%40microsoft.com%7Ca9174eb049984dbf19f308d91bdc8911%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637571456275013632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tjbBxQ7jPbBBNhNTbdY2tXpvgHI9m%2FGOKBqWV794HBI%3D&reserved=0). Alex Simmons has [recently shared further details on how to start migrating](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/have-you-updated-your-applications-to-use-the-microsoft/ba-p/1144698) your apps from ADAL to MSAL. We’re reaching out to see if you are aware of this deprecation and where you are in your migration journey.

1.	How can we best support you in your migration journey? Is there an additional information and support we can provide to you?
2.	When will you begin migrating your app?

### Why migrate to MSAL?
+	**Resilience improvement:** MSAL is in progress to provide the support for better recovery from infrastructure or service disruptions from Azure Active Directory. Some key resilience features like token caching, proactive token refresh, AAD regional isolation(ESTS-R) and client throttling are supported or work in progress with MSAL. Find more details on resilience onboarding and feature support on overview of Azure AD resilience.
+ **Security improvements:** Any application using ADAL or other library would not be able to have the latest security updates which can have serious security implications. After the ADAL end of life in June 2022, no new security patches would be released.
+	**Feature advancement:** MSAL supports the state-of-the-art authentication features, like ‘incremental consent ’ and ‘’Single Sign-on’ to mention a few. ADAL does not support above mentioned features, so applications would not be able to utilize these to keep up with the advancement in Identity ecosystem. No new features updates for ADAL starting June 2020.

#### Resources
-	Migration Guidance and Documentation: [Migrating applications to the Microsoft Authentication Library (MSAL) | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration#migration-guidance)
-	Link to our FAQs wiki: [MSAL Migration FAQ | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration#frequently-asked-questions-faq)
    -	Need help? For any questions, open issues, and feature requests, let us know through Microsoft Q&A by using the tag azure-ad-adal-deprecation or azure-ad-graph-deprecation.  
    -	Got feedback? As always, we’d love to hear any feedback or suggestions you may have. Please let us know what you think in the comments below or on the [Azure AD feedback forum](https://feedback.azure.com/forums/169401-azure-active-directory).

Thanks,
**Auth SDK vTeam**

**Comment by Rinki-MSFT** [comment]
The final deadline to migrate applications to Microsoft Authentication Library (MSAL) has been extended to June 1, 2023. Here is the [the official announcement](https://aka.ms/adal-eos)

**Comment by raman-m** [comment]
@ShannonCanTech Dear Mr. Foster,
@Rinki-MSFT Hi Rinki!

I cannot get it, why did you create this issue in our repo?
Ocelot app uses Auth and Identity features of .NET framework as sidecar. So, only developers are responsible for their final Auth solutions. They should care about any Identity services including Azure, ADAL, MSAL. If you look into our docs then you'll see we recommend to use code snippets and code recipes which were taken from official MS Learn portal.
If your portal is updated, then our contributors will see also. ))
Only some specific .NET framework upgrading issues can occur, which we try to track to recommend our community as migration instructions. But this is very specific and not related to Azure services.
Finally, I would say this ads ticket cannot be approved for development, because it's not a feature, it's not a bug. It is announcement notification.
Thanks for notifying us 2+ years ago! 😺 

### P.S.
We recommend Identity Server as SSO & token signing service. We haven't any Azure specific modules and docs for identity management as common practice for Ocelot developers. Users express low interest in Azure services integration directly as Ocelot modules and packages. But if your Microsoft engineers will help us doing such integrations, we will appreciate opening  PRs in future. Thanks!
