### ISSUE TITLE
This project seems to have been abandoned ?

### ISSUE THREAD

**Issue by EngRajabi** [ThreeMammals/Ocelot#1525]
This project seems to have been abandoned. It has not been updated for a long time and its mesh replay is full of requests

**Comment by Arthusppp** [comment]
https://dotnet.libhunt.com/ocelot-alternatives

**Comment by itsbibeksaini** [comment]
Hi @EngRajabi 

There is not development since almost a year now on this project so seems like your speculation is correct.
However, to have some alternative strategies you can leverage out Consul service mesh or Istio.

**Comment by default-kaas** [comment]
> This project seems to have been abandoned. It has not been updated for a long time and its mesh replay is full of requests

> Has Ocelot completely stopped maintenance

On October 23th 2021  I emailed the head maintainer @TomPallister 
And his response was the following:
```
Unfortunately I just don’t have enough time to maintain Ocelot. 
```
Then in response to this  i asked him on October 23th  what his future plans where for Ocelot,
But he did not respond to it.

I sent him an email again on November 24th and he still did not respond to it.
So I think this quote still holds true.
```
Unfortunately I just don’t have enough time to maintain Ocelot. 
```

A little bit of background information for others, the last release for Ocelot was on December the 11th 2020. Tom Pallister also started a [blog](https://threemammals.com/blog/) for Ocelot with a post on February the 4th 2021, where he posted the following:

![image](https://user-images.githubusercontent.com/23498867/145048313-4d852095-8dd5-4cf5-97cf-6bbb5aba6e8a.png)

Since then he has posted nothing on this blog.

**Comment by raman-m** [comment]
@EngRajabi  Mohsen!!!
