### ISSUE TITLE
How to optimize ocelot startup time.

### ISSUE THREAD

**Issue by heizel184** [ThreeMammals/Ocelot#1526]
Hi I am using Ocelot 15.0.6 as a gateway. Since Ocelot supports multiple configuration files. Previously I include seven different configurations files with the routes of different projects API, The problem occurred when a new file is added with more than 80 routes in it. After adding that file The ocelot took too long at startup that the application got stuck and shut down later when deploying gateway.

The current behavior of ocelot is unacceptable, application should not take much time for a startup. How can I optimize that time or speed up the startup time of ocelot at production?

## Steps to Reproduce the Problem
Add multiple configuration files with a large no of routes
## Specifications

  - Version: 15.0.6

**Comment by ks1990cn** [comment]
@raman-m Interesting, how we can test it? Is there any test cases for this thing?

**Comment by ks1990cn** [comment]
@heizel184 are you still facing it on latest versions?

**Comment by raman-m** [comment]
@heizel184  Dear Hina!
Thanks for reporting it!

Your issue is quite outdated because of legacy version 15.0.6.
Could you upgrade your solution to the latest version and check the issue once again please?

----
> The problem occurred when a new file is added with more than 80 routes in it.

Are you sure that all files are valid? So, have all these files valid JSON formatting and syntax?
Can you attach all config to the issue plz?

-----
> After adding that file The ocelot took too long at startup that the application got stuck and shut down later when deploying gateway.

Deployment can fail because of critical error when starting up the app...
Can you attach Ocelot log please?
