### ISSUE TITLE
Has Ocelot completely stopped maintenance？

### ISSUE THREAD

**Issue by winlj** [ThreeMammals/Ocelot#1539]
Has Ocelot completely stopped maintenance

**Comment by default-kaas** [comment]
> Has Ocelot completely stopped maintenance

On October 23th 2021  I emailed the head maintainer @TomPallister 
And his response was the following:
```
Unfortunately I just don’t have enough time to maintain Ocelot. 
```
Then in response to this  i asked him on October 23th  what his future plans where for Ocelot,
But he did not respond to it.

I sent him an email again on November 24th and he still did not respond to it.
So I think this quote still holds true.
```
Unfortunately I just don’t have enough time to maintain Ocelot. 
```

A little bit of background information for others, the last release for Ocelot was on December the 11th 2020. Tom Pallister also started a [blog](https://threemammals.com/blog/) for Ocelot with a post on February the 4th 2021, where he posted the following:

![image](https://user-images.githubusercontent.com/23498867/145047827-b42ea6f0-df53-47d1-8e54-26e0138e0322.png)

Since then he has posted nothing on this blog.

**Comment by wayne-o** [comment]
Considering this is an OSS project and in the spirit of that we are allowed to branch from it and continue the endevour - is there any appetite in doing so? 

Things (IMO) to consider include the fact that MS are currently building out Yarp (https://github.com/microsoft/reverse-proxy) which looks promising, the level of commitment would also be fairly high, especially considering the 471 current issues and 78 PRs (at time of writing).

I'd be interested in seeing if anyone would be up for continuing the development of Ocelot since we use it in a few apps and I think it's a good bit of work worth keeping around.

**Comment by ggnaegi** [comment]
@wayne-o Maybe a group of developers would be up to the task? I've worked with ocelot for a year now. It's easy to use, but I had to fork it for my needs (tweaking polling).

**Comment by winlj** [comment]
ok  i see

**Comment by wayne-o** [comment]
> @wayne-o Maybe a group of developers would be up to the task? I've worked with ocelot for a year now. It's easy to use, but I had to fork it for my needs (tweaking polling).

Yep this is what I am aiming for - if we can get enough interest perhaps there's some mileage in continuing the effort.

**Comment by Abe-Froman** [comment]
With 2 releases since this issue was last touched, including a major, I wonder if things have changed. @TomPallister can you comment which may address also #1328?

**Comment by vitorelli** [comment]
I emailed the head maintainer @TomPallister last week, unfortunately I did not receive any reply.

**Comment by raman-m** [comment]
> @winlj commented [on Nov 25, 2021](#issue-1063247253)

**No!** Not "completely" and not "stopped"
Current release: [20.0.0](../releases)
NuGet package: [20.0.0](https://www.nuget.org/packages/Ocelot/20.0.0)

**Comment by raman-m** [comment]
@winlj
Not an issue anymore! 😉

**Comment by raman-m** [comment]
> @vitorelli commented [on May 2, 2022](#issuecomment-1114840119)

Hi Alexandre!
What's your question?
