### ISSUE TITLE
 Character Match issue  

### ISSUE THREAD

**Issue by MetinTAPAN58** [ThreeMammals/Ocelot#1546]
## Expected Behavior / New Feature

UrlPath and Character Matching shouldn't be a problem

## Actual Behavior / Motivation for New Feature

Character match issue happens because of not using the rules of the invariant culture
 
## Specifications

  - Version: 13.5.2 

## Fixed in my solution:
- [Ocelot/DownStreamRouteFinder/UrlMatcher/](https://github.com/ThreeMammals/Ocelot/tree/develop/src/Ocelot/DownstreamRouteFinder/UrlMatcher)
	 	   
Changes will be required to the [CharactersDontMatch](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs#L134) method in [UrlPathPlaceholderNameAndValueFinder.cs](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs)

`ToLowerInvariant` was used instead of `ToLower`.
```csharp
	private bool CharactersDontMatch(char characterOne, char characterTwo)
	{
		return char.ToLowerInvariant(characterOne) != char.ToLowerInvariant(characterTwo);
	}
```
And
- [Ocelot/DownStreamRouteFinder/UrlMatcher/](https://github.com/ThreeMammals/Ocelot/tree/develop/src/Ocelot/DownstreamRouteFinder/UrlMatcher)
	
Changes will be required to the `Match` method in [RegExUrlMatcher.cs](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/DownstreamRouteFinder/UrlMatcher/RegExUrlMatcher.cs):
`Regex.IsMatch` was used instead of `pathTemplate.Pattern.IsMatch` 
```csharp  	
	public Response<UrlMatch> Match(string upstreamUrlPath, string upstreamQueryString, UpstreamPathTemplate pathTemplate)
	{
		if (!pathTemplate.ContainsQueryString)
		{
			return Regex.IsMatch(upstreamUrlPath, pathTemplate.Pattern.ToString(),RegexOptions.CultureInvariant)
				? new OkResponse<UrlMatch>(new UrlMatch(true))
				: new OkResponse<UrlMatch>(new UrlMatch(false));
		}

		return pathTemplate.Pattern.IsMatch($"{upstreamUrlPath}{upstreamQueryString}")
			? new OkResponse<UrlMatch>(new UrlMatch(true))
			: new OkResponse<UrlMatch>(new UrlMatch(false));
	}
```

**Comment by ks1990cn** [comment]
Hi @MetinTAPAN58 ,

Its already there what you want you just need to set your property `RouteIsCaseSensitive`. Its tested okay on this test case -  https://github.com/ThreeMammals/Ocelot/blob/bb795876c493af958f1d58c852ea56e94263906d/test/Ocelot.AcceptanceTests/CaseSensitiveRoutingTests.cs#L53

@raman-m we can close this issue I think.

**Comment by raman-m** [comment]
@MetinTAPAN58 
Dear Metin!

First issue is obsolete. The [ToLower method](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs#L136) is used in develop branch now.
I don't understand, do you need `ToLower` or `ToLowerInvariant`? What culture is set up on your Ocelot app machine?
For English culture there are no differences between both of them. Probably you used non-English culture on your machine.

Second issue was fixed in commit https://github.com/ThreeMammals/Ocelot/commit/9bbb6364f2b73afac04e724d69bcc14d39c13a05

If it will still be important for you, you are welcome to reopen issue with more details.
