### ISSUE TITLE
Define gateway Routing configurations in the code

### ISSUE THREAD

**Issue by badjuice** [ThreeMammals/Ocelot#1637]
## New Feature
Defining up the reroute endpoints in code, using the builder design pattern, for example.
In code it'd be something similar to putting the routes in a `.json` or `.yml`.

## Motivation for New Feature
It'd be easier to visualize and break down into smaller classes, the definitions of of the routes. A long `.json` file with every single configuration when they tend to be different can be difficult to mantain.

**Comment by raman-m** [comment]
Hi Nuno!

You want to write C# code as Routes classes instead of writing routes in **ocelot.json** file, right?

First,
Do you understand that having hardcoded routes in C# classes you must compile, build and deploy your entire gateway solution to some hosting environment each time having even a small change in these routes classes?

Second,
Note, that **ocelot.json** file can be changed on the fly when gateway is running. So, there is hot reload feature for **ocelot.json**. In this case you need not to redeploy the gateway instance.
More about hot reload here: [Reload JSON config on change](https://ocelot.readthedocs.io/en/latest/features/configuration.html#reload-json-config-on-change)

Third,
If your routes number increases then it make sense to consider to introduce [**CatchAll**](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) routes which will process all traffic for entire web service instance (Docker container). I don't think you will have dramatic number of services instances.

Fourth,
Do you know about the [Merging configuration files](https://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files) feature?
Usage of this feature will bring exactly what you want: to split large config into a number of smaller configuration files for easier support and development via Git versioning. You can provide a suffix in the name of config file to track a file as a logical piece of functionality.

Finally,
Your feature request is overhead one. It will take some valuable effort to implement. But idea is interesting!
We can consider implementation of middleware which can read Routes definitions from another DLL-file as NuGet package or separate project in the solution.
Anyway, it should be discussed...

**Comment by raman-m** [comment]
@badjuice  Hi Nuno!
It seems you are **not** interested in a discussion...

Your user case is similar in something to #1665 where Christofer requested to have multiple Routes config files.
You would like more control on Route when defining them as C# classes/code in comparison to having a `.json` or `.yml` files.

So, I see that you would like to write C# code and manage the routes.
In this case I would recommend you to consider [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) feature/approach where you control all services and their routes. You can use Consul or Eureka, or another service provider you love.

Finally, I would say that you need to try another great feature of Ocelot which is [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing)!
This feature allows you to get all services from a service discovery provider (for example, from Consul) by the service name key, and register all services as routes dynamically! Pay attention that Ocelot works here in special mode of Dynamic Routes. So, it is impossible to mix static routes and dynamic routes modes!
Well... Usage of dynamic routes doesn't allow you write C# Route classes. But I believe you can design and develop some client which will register your services in service discovery, and after that your "dynamic config" will be deployed by Dynamic Routes mode of Ocelot.

P.S. I suggest you to develop new `AddRoute` method  for `IOcelotBuilder` interface, and I believe it will be possible to register static/dynamic route from the C# code.

If you will have some real working code we will accept and review your PR with pleasure in future!

For now this issue is going to be closed...
