### ISSUE TITLE
Is not possible have multiple config file for multiple environment 

### ISSUE THREAD

**Issue by cfasol** [ThreeMammals/Ocelot#1665]
## Expected Behavior / New Feature
I'd like to add a config file for each micro-service broken down by each environment.
Ex: 'ocelot.service.json' the general one, 'ocelot.service.env.json' more specific one that override the first one.

## Actual Behavior / Motivation for New Feature
Currently is possible add multiple config file via folder but is not possible specify the overwrite for each environment.

## Steps to Reproduce the Problem

  1. create a folder tha contains your ocelot configs files
  2. create a copi of your config file with this patten: 'ocelot.service.env.json'
  3. run api-gateway project, the application throw an exception
  

## Specifications

  - Version: 19.0.2
  - Platform:  .net core 7.0
  - Subsystem: MacOs

**Comment by raman-m** [comment]
Hi Cristopher!

Have you read this docs: [Multiple environments](https://ocelot.readthedocs.io/en/latest/features/configuration.html#multiple-environments) ?
Give a try, and let us know your results please?

**Comment by raman-m** [comment]
@cfasol 
Have you heard my advice, and have you provided settings for [multiple environments](https://ocelot.readthedocs.io/en/latest/features/configuration.html#multiple-environments)?
You have one more week.

Let's find some workaround within one week please!
Your issue will be accepted or declined until June 23.
---

**Comment by raman-m** [comment]
> run api-gateway project, the application throw an exception

Sorry, what's the exception?
Could you upload your gateway solution to GitHub please?
That's how it will be possible to review your user scenario.

**Comment by raman-m** [comment]
Hi Cristopher!
It is time to decide on your feature request...
Here are my thoughts.
> ## Expected Behavior / New Feature
>I'd like to add a config file for each micro-service broken down by each environment.
> Ex: 'ocelot.service.json' the general one, 'ocelot.service.env.json' more specific one that override the first one.

## First,
Why do you want to extract some particular Route for some environment and place it into separate file?
What's the reason/goal?

## Second,
Pay attention that current implementation has well-known, developed, tested configuration structures and data models.
Your feature request will require tons of code refactoring, rewriting unit tests, and for sure changing a lot of acceptance tests.
For a what goal?
In addition, we must update all Ocelot documentation. This is just huge massive feature request for unclear goal...
Just crazy idea!

## Third,
Pay attention that we have now Hot Reload feature for **ocelot.json** (all configuration in one file): [Reload JSON config on change](../blob/develop/docs/features/configuration.rst#reload-json-config-on-change)
People can upload new updated config files via [Administration API](https://ocelot.readthedocs.io/en/latest/features/administration.html) for the live gateway!
I am afraid we should update this feature also, to track multiple config files. So, Administration API should be updated too!

## Finally,
I would say that this feature request leads to abnormal project update with a huge refactoring.
But if you have some draft or real working solutions in your repos, just fork the Ocelot repo, create feature branch, experiment and develop, and come to us back in future with your PR (with this issue reopening), and we will consider this functionality.
Good luck!

For now this issue is going to be closed...
