### ISSUE TITLE
502 Bad gateway with https downstream scheme

### ISSUE THREAD

**Issue by ljubomir-bacovic** [ThreeMammals/Ocelot#1667]
Hello,

I am having and issue when my routes use https as downstream scheme:

"DownstreamScheme": "https",
"DownstreamHostAndPorts": [
    {
       "Host": "localhost",
       "Port": 7001
    }
    
I am getting 502 error. When I use http and port 5001, I don't get any error.

**Comment by raman-m** [comment]
Hi Ljubomir!

There is a lack of information to help you! I cannot accept this issue for now!

I believe your issue is related to hosting environment. Try to check that direct connection from the client to the service is working. 
After that you need provide complete and correct ASP.NET Web API app configuration for gateway project.
See more about configs: [Configuration](https://ocelot.readthedocs.io/en/latest/features/configuration.html)
Sure you have to deploy the app correctly too. If you use Docker deployment you have to create Docker Compose project inside of the Visual Studio solution and place/register all services projects to/in Docker Compose project.
If you use **https**-scheme in the **DownstreamScheme** option you have to create SLL certificates and/or make a self-signed SSL-certificate and install it at hosting environment.
But I don't recommend you to use **https** for development environment. Just use **http** scheme.
For Staging and Production environment you have to buy or make completely valid SSL certificates and install them at hosting machine.

Good luck in your endeavor with Ocelot!

**Comment by raman-m** [comment]
Ljubomir!
Let's find some workaround within one week please!
Your issue will be accepted or declined until June 13.
---

**Comment by raman-m** [comment]
Sorry, @ljubomir-bacovic !
I'm going to close the issue...

Hope you like Ocelot gateway, and you will use Ocelot in your future projects.
