### ISSUE TITLE
Result Aggregation Chaining

### ISSUE THREAD

**Issue by aaronscribner** [ThreeMammals/Ocelot#1668]
## New Feature
Request Aggregation Call Chaining

## Motivation for New Feature
We have the need to retrieve a sorted and paged set of data from one microservice and use the data from this call subsequent calls to other microservices.

E.g.

(This is a hypothetical example to demonstrate the need to chain calls)

For a menu system for a Coffee Shop, we sell both drinks, hard goods, and pre-made items. When we want to display related items for one of the categories, we need to pass the identifiers to the other microservice.

BFF - /api/menus/{menu-id}?sort=name&page=1&size=10

BFF -> Drink Service GET /api/drinks?sort=name&page=1&size=10
BFF -> Hard Goods Service GET /api/hard-goods?relations=1,...,n

Here the BFF has to know the 10 items from the drinks based on the sort order and paging to know which identifiers to use in order to find related products.

Is there a way in Ocelot to have a subsequent call for aggregation be dependent upon data returned from a previous call?

This is almost like "promise chaining" in jscript. I understand reasons to avoid this, but given the business model for my employer, this type of scenario is necessary.

I am trying to determine if we can use Ocelot for this or if we need to write our own aggregation pattern.

**Comment by raman-m** [comment]
> Is there a way in Ocelot to have a subsequent call for aggregation be dependent upon data returned from a previous call?

**No**. There is no way! Practically, but in theory...
The [Request Aggregation](https://ocelot.readthedocs.io/en/latest/features/requestaggregation.html) feature was designed for parallel requests only. You can combine content data of multiple parallel routes into one aggregated response. There is no content data processing and parsing of downstream responses, only combining. In this case there are no dependencies between parallel routes. So, this is parallel workflow execution.
"**Subsequent call**" means we build sequential workflow with dependencies. It is hard to implement some kind of sequential workflow processor. The clients should care about this sequential workflows.
More about sequentioal workflow problem here: [issue 1070 feedback](1070#issuecomment-1535140655)
- #1070 

Also, there is no way to describe sequential Aggregation/Workflow by ocelot configuration.

Finally, 
In theory, implementation of sequential workflow being processed by Ocelot requires your development and enhancement of gateway pipeline. And anyway you will need to implement parsers/extractors to substitute data to other routes.
You can try to build custom Aggregators as BFF solution by implementation of the [IDefinedAggregator](https://github.com/search?q=repo%3AThreeMammals%2FOcelot%20IDefinedAggregator&type=code) interface with injection.
Pay attention that parsing logic will be on the gateway side, which is bad because of slowing down the performance of gateway.

**Comment by aaronscribner** [comment]
Thank you @raman-m 

Yes, we are aware of the pros/cons of this approach. We were not seeing that it is possible and I wanted to check to make sure we were not missing something.

Much appreciated.

**Comment by raman-m** [comment]
Duplicate of #1070 !
No good user scenario description.
