### ISSUE TITLE
Bump to Polly 8.0

### ISSUE THREAD

**Issue by RaynaldM** [ThreeMammals/Ocelot#1712]
## Bump to Polly 8.0
and make some code improvements in Ocelot.polly package

**Comment by raman-m** [comment]
Ray,
I still cannot get it, why did Tom create a separate project with publishing to NuGet, just for Polly lib integration?
Also, `Ocelot.Provider.Polly` is not true Ocelot provider, because the term provider we use for Service Discovery feature in the namespace `Ocelot.Provider` of the projects **Ocelot.Provider.***
Many ASP.NET projects just add the [Polly package](https://www.nuget.org/packages/polly/) directedly to the same project.

In my opinion we can easily include the Polly package right to Ocelot project and remove the Polly Provider project.
