### ISSUE TITLE
Add Global Configuration to ocelot.json  file in AddOcelot function

### ISSUE THREAD

**Issue by ali0saeedi** [ThreeMammals/Ocelot#1794]
## Expected Behavior / New Feature
If global configuration is added to the config folder we expect the config will copy to the aggregated ocelot.json file.

## Actual Behavior / Motivation for New Feature
In the global configuration section, null values will be inserted in ocelot.josn file.

## Steps to Reproduce the Problem

  1. add global configuration instructions to the AddOcelot function in Ocelot.DependencyInjection

## Specifications

  - Version: 20.0.0.0
  - Platform: .Net 7
  - Subsystem: Ocelot.DependencyInjection

**Comment by ali0saeedi** [comment]
you should name your config file to ocelot.global.json in config folder

**Comment by raman-m** [comment]
Dear Ali,
We don't understand your user scenario! No information on environment.
Ocelot is based on and optimized for Docker deployments and scaling...

We cannot accept this feature request! If this is a bug, provide more details on the user scenario please!

I recommend to discuss your user scenario first in [Discussion](https://github.com/ThreeMammals/Ocelot/discussions) space.

Formally you violated [development process](https://ocelot.readthedocs.io/en/latest/building/releaseprocess.html) because it is not discussed, and [your GitHub account](https://github.com/ali0saeedi?tab=repositories) has no Ocelot as forked repo, which means you are newbie in Ocelot development.

**Comment by raman-m** [comment]
@ali0saeedi commented [on Nov 21](#issuecomment-1820516430):
> you should name your config file to ocelot.global.json in config folder

Learn more: [Merging Configuration Files](https://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files)
