### ISSUE TITLE
File-scoped namespace

### ISSUE THREAD

**Issue by LassazVegaz** [ThreeMammals/Ocelot#1874]
## Expected Behavior / New Feature
Change block-scoped namespaces to file-scoped namespaces

## Actual Behavior / Motivation for New Feature
Increase code readability. This can be done easily by using the `Code Cleanup tool` in VS.
For new file additions, VS can be configured to automatically add file-scoped namespaces instead of block-scope namespaces.

If this is approved, I am willing to do it.

## Steps to Reproduce the Problem
_N/A_

## Specifications
_N/A_

**Comment by raman-m** [comment]
Lasindu,
Thanks for pointing attention to this issue with namespaces!

As a team, we know about this problem of namespace declaration inconsistency. 

I agree, it is better to have file-scoped namespaces because each file should have single class or type as Microsoft conventions requires for C# development. We define file-scoped namespaces for a newly created **.cs** files. Sometime converting old files.
But this issue is minor in my opinion, and as a team, we try to focus on real problems and feature development. 😉 
Going to mark as minor issue...

**Comment by raman-m** [comment]
@ggnaegi @RaynaldM Your opinion?
Will we let the contributor to change tons of files? 🤣

**Comment by raman-m** [comment]
@LassazVegaz Please [add me as collaborator](https://github.com/LassazVegaz/Ocelot/settings/access) to your forked repo! Without a question Why.

**Comment by LassazVegaz** [comment]
I don't see this in your license and I don't like your tone. I would rather delete the fork.
I am just trying to contribute here as a serve to the community and here you are telling me what to do with no respect.

**Comment by raman-m** [comment]
Sorry, what license are you talking about?
If you don't want to add me to your fork, I'm OK with this your decision. Our process don't require add team members to the forks. This is your personal decision add other collaborators to some forks.

What I don't like is when people arguing having nothing done, both bad and good too.
I haven't nothing bad done.
I am repository manager, and I know what I do.

**Comment by LassazVegaz** [comment]
You changed your comment where you had said
> [add me as collaborator](https://github.com/LassazVegaz/Ocelot/settings/access) to your forked repo! __Without a question why__
