### ISSUE TITLE
Ocelot.Provider.Consul: The `GetDownstreamHost` method inefficiently checks the node object

### ISSUE THREAD

**Issue by pkutsch** [ThreeMammals/Ocelot#2203]
**Expected Behavior:**
Ocelot.Provider.Consul works once properly configured as described at:
https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html

**Actual Behavior:**
Posting to API Gateway with Ocelot configured throws Bad Gateway 502 error. Note that without Ocelot.Provider.Consul configured, the API Gateway works without any issue i.e. if 'DownstreamHostAndPorts' is used and no 'ServiceDiscoveryProvider' is configured in ocelot.json.

Performed VS debugging and found that the cause was at line 97 of DefaultConsulServiceBuilder.cs in Ocelot.Provider.Consul project:

_=> node != null ? node.Name : entry.Service.Address;_

![OcelotProviderConsul_NodeName](https://github.com/user-attachments/assets/96b2ef0f-1b2e-41f2-b403-10c79e643c42)
![OcelotProviderConsul_BadGatewayException](https://github.com/user-attachments/assets/26657bfb-dee0-4457-b5ef-17eb20761c00)

Was able to fix the exception by replacing **node.Name** with **node.Address**. 

Thought of editing the code and sending a pull request, but since I do not understand why there is a null reference check on the node object (being new to both Ocelot and Consul), I decided better to submit an issue instead, so someone with more knowledge regarding this code logic can apply a proper fix. 

Versions:
.Net Core 8
Ocelot 23.3.6 (nuget package)
Ocelot.Provider.Consul 23.3.6 (nuget package)
Consul 1.20.0
Windows 10 (os of development environment)

**Comment by raman-m** [comment]
>Thought of editing the code and sending a pull request, but since I do not understand **why there is a null reference check on the node object** (being new to both Ocelot and Consul)

Well... Please note that since version [13.5.2](https://github.com/ThreeMammals/Ocelot/releases/tag/13.5.2) and #909, when the node name became the host name as Ocelot's best practice, now since [v23.3](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0), we configure Consul service building by the proposed #2067 feature aka `DefaultConsulServiceBuilder` class. So, **the subject of discussion**:
https://github.com/ThreeMammals/Ocelot/blob/da9d6fab6c704baa925d3c1c5fc984f6a9e9c717/src/Ocelot.Provider.Consul/DefaultConsulServiceBuilder.cs#L96-L97

I know this check is not ideal and looks strange. But what do you propose? Have an idea in mind? What are the best practices for organizing Consul services into a node group? I have the following idea, which makes real sense:
```diff
-     => node != null ? node.Name : entry.Service.Address; 
+     => !string.IsNullOrEmpty(node?.Name) && !node.Name.Equals("default") ? node.Name : entry.Service.Address;
```
So, my idea is to identify more practical use cases when DevOps engineers organize services into a Consul node and let this be a best practice in Ocelot integration with Consul.

> I decided better to submit an issue instead, so someone with more knowledge regarding this code logic can apply a proper fix.

Yes, please! But I guess this PR will be a micro one: we are limited to the re-implementation of the virtual `GetDownstreamHost` method only. Let's discuss my idea while honoring yours...

**Comment by ggnaegi** [comment]
@raman-m same behavior here, I'm not able to switch to latest 23.4.0 and i have to keep working with 23.2.2. It's another solution we have deployed, I was updating the oidc parameters... And I thought why not try 23.4.0? No luck here.

**Comment by raman-m** [comment]
@ggnaegi Dear Guillaume , don't cry that your customers just f..ed you these days.

To be more constructive...
> same behavior here, 

What is the "same"? Did you read the author's concern? The author does not understand the rather unclear null-checking of the `Node` object, which is actually not null due to the following getting Node data: 
https://github.com/ThreeMammals/Ocelot/blob/da9d6fab6c704baa925d3c1c5fc984f6a9e9c717/src/Ocelot.Provider.Consul/Consul.cs#L34
Thus, the node is indeed not null, and I concur with the author that this logic could be improved. I have requested the author to articulate his ideas in accordance with best DevOps practices, but I have received no feedback. 
What is your perspective on the best DevOps practices for utilizing node groups in Consul?

> I'm not able to switch to the latest 23.4.0 and i have to keep working with 23.2.2.

Lazy bones! Don't have a test server? Ask your rich client to buy some hardware or cloud-machine.

> It's another solution we have deployed

Is that so? Are you certain? How did verify this? What evidence do you have to support your claim? My refactoring in #2067 was entirely based on the current unit and acceptance tests. It have been impossible to release if the old tests had failed. Therefore, the original functionality in the Consul provider remains intact. All details are outlined within the PR; did you take the time to review it?

Once [again](https://github.com/ThreeMammals/Ocelot/issues/2203#issuecomment-2477122965):
> Well... Please note that since version [13.5.2](https://github.com/ThreeMammals/Ocelot/releases/tag/13.5.2) and #909, when the node name became the host name as Ocelot's best practice, now since [v23.3](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0), we configure Consul service building by the proposed #2067 feature aka `DefaultConsulServiceBuilder` class.

I will explain that the service building was moved from the `Consul` class to the `DefaultConsulServiceBuilder` class. However, the main logic of initialization remained unchanged. Did you notice any changes? Finally, the `Node` object was not null even in the old code prior to #2067❕ 

>  I was updating the oidc parameters...

I do not understand you! Are these params of Consul? How is this property connected to Ocelot code? Please provide actual lines of code. What changes have been made?

> And I thought why not try 23.4.0?

Why not? Just update! But seems your client is capricious and strict, so better to ask the client to deploy Testing environment.
Sorry, I can't help you in this.

> No luck here.

What do you mean by "no luck"? Our project and the Ocelot product should evolve! There are times when I strongly believe that it would be more prudent for you to continue using version 23.2.2 and refrain from disturbing me.

Your previous concerns in https://github.com/ThreeMammals/Ocelot/pull/2067#issuecomment-2115152150 were not addressed because I cannot focus on the Consul provider only. On the other hand, did you assist me? It seems not, correct? In https://github.com/ThreeMammals/Ocelot/pull/2151#pullrequestreview-2344137072, you informed me that you had a testing plan, but what are the results of that testing? Two months have passed since October 3.

**Comment by raman-m** [comment]
@pkutsch Where are you?

**Comment by ggnaegi** [comment]
@raman-m I think you misunderstood me. I have two projects, one with Consul service discovery, the other without. I was configuring a new oidc identity provider for the first project, and I thought, while at it, let's update to the latest ocelot version (I'm still using 23.2.2 for this project, i tried 23.3.x, but it never worked). Unfortunately it still doesn't work!

**Comment by ggnaegi** [comment]
@pkutsch @raman-m Ok, the problem here is that you can get a dns host name, but you might want to customize it... and then... It doesn't work anymore.
https://developer.hashicorp.com/consul/docs/agent

> Node name: This is a unique name for the agent. By default, this is the hostname of the machine, but you may customize it using the [-node](https://developer.hashicorp.com/consul/docs/agent/config/cli-flags#_node) flag.

**Comment by raman-m** [comment]
@pkutsch @ggnaegi What is the default name of the single node group in Consul after installation? I mean, the default settings. Is this name empty, or does it have some predefined value? I agree that users (not C# developers) probably want a JSON option in `ocelot.json`. But for C# developers, there are no problems at all: `DefaultConsulServiceBuilder` can be customized in any way.

#### P.S.
I am not interested in engaging in any discussions here. I believe we cannot enhance further in this context. The DNS probe check should be delivered in #2208. This issue will be closed because the author has received the desired answer with the actual C# recipe
