### ISSUE TITLE
EnableContentHashing should be default true (cache issue)

### ISSUE THREAD

**Issue by wast** [ThreeMammals/Ocelot#2234]
## Expected Behavior / New Feature
EnableContentHashing should be default true because before the ocelot had this implicitly enabled.

## Actual Behavior / Motivation for New Feature
EnableContentHashing should be default true because before the ocelot had this implicitly enabled.

## Steps to Reproduce the Problem

  1. Have Ocelot version 21 or older in your system
  2. Have some Ocelot caching configured for some POST request with different payloads
  3. Cache works as described by Documentation
  4. Upgrade Ocelot to latest version (23.*) and now cache doesn't update based on POST payload, causing same response for different requests, causing total panic in both your engineering and business teams.

## Specifications

  - Version: 23
  - Platform: any
  - Subsystem: caching

This feature is mentioned in Documentation as a breaking change but isn't shown in release notes as breaking change.

Looking for opinions.
Can also open a PR if you guys agree.

**Comment by raman-m** [comment]
> This feature is mentioned in Documentation as a breaking change but isn't shown in release notes as breaking change.

It is highly recommended to read the Release Notes and Documentation. Please review the [23.3.0 Notes](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0) once again as the **Breaking Changes** section has been added with an official notice to the community. Also, updating the [Caching documentation](https://ocelot.readhedocs.io/en/23.36/features/caching.html) is not needed as it is solid and complete.

> Can also open a PR if you agree.

It is not necessary, as the problem has been addressed by #2058. Developers and users who read the documentation can easily upgrade to the new version by updating the global configuration.

>### Expected Behavior / New Feature
>EnableContentHashing should be default true because before the ocelot had this implicitly enabled.

It should not, because other users may come to us with new reports. It is a bit late: The team has discussed this and the decision was made to favor performance over backward compatibility. Additionally, the community was instructed on how to upgrade to v23.3+ in the documentation. In worst case, users can switch off caching altogether to have stable original behavior.
I would say that users decide what they prefer: performance, caching, or original behavior of downstream services.

**Comment by raman-m** [comment]
The issue can't be accepted because POST requests should NOT be cached at all❗
