### ISSUE TITLE
Provide DelegatingHandler through DI

### ISSUE THREAD

**Issue by mjrousos** [ThreeMammals/Ocelot#259]
## New Feature
Currently, all services needed for my ASP.NET Core app are provided via dependency injection except for `DelegatingHandler`s used by Ocelot. Those are explicitly created in `AddDelegatingHandler` calls.

I can make my `DelegatingHandler`s available in the DI container (`services.AddScoped<DelegatingHandler, MyCustomHandler>();`) but there's no elegant way to use DI-registered delegating handlers with Ocelot.

This is especially important in cases where the custom `DelegatingHandler` constructor takes a DI-provided parameter. 

Two ideas for how this could be made better would be:

1. Add a generic `AddDelegatingHandler` overload that just takes the type of the `DelegatingHandler` to be used.
    1. `AddDelegatingHandler<MyCustomHandler>()`
1. Add an overload of `AddDelegatingHandler` that takes a `ServiceProvider` as an input parameter into its `Func` so that users can retrieve other DI-provided objects when creating their handlers.
    1. `AddDelegatingHandler(sp => { var foo = sp.GetRequiredService<Foo>(); return new MyCustomDelegatingHandler(foo); });`

**Comment by TomPallister** [comment]
@mjrousos thanks for your interest in the project.

I agree with everything! Will take a look at the code and see if I can make the API provide one of the options.

**Comment by TomPallister** [comment]
@mjrousos I've pushed something up that just provides a method over AddSingleton<T> with a constraint for DelegatingHandlers. I still need to tidy it up a bit and not sure about leaving AddDelegatingHandler(Func<DelegatingHandler> handler) as this is misleading because only singleton will work as we cache the HttpClients because of socket exhaustion.

Also you could just add delegating handlers into into the container now as services.AddSingleton<DelegatingHandler, FooHandler>(); so maybe we dont need the method over it...not sure!

Anyway feel free to check the PR and let me know if I've missed anything.

**Comment by TomPallister** [comment]
decided to remove the func way of adding handlers, through container is much better.

**Comment by TomPallister** [comment]
close after release

**Comment by TomPallister** [comment]
Ive just pushed version 4.0.0 that should fix this. I have updated major version because I have taken away the api that passed in func.

**Comment by mjrousos** [comment]
Looks good; thanks for the update!
