### ISSUE TITLE
About request Timeout

### ISSUE THREAD

**Issue by BowAngel** [ThreeMammals/Ocelot#318]
I have a question for timeout:

We have a back-end reporting service and it will execute the request slowly. One of its actions will cost about 2 minutes and I find an issue that this action will return HTTP 404. I check the service's logs and find the reason is Ocelot will cancel to wait so long time and return 404 when it waits after 1 minute 30 second.

I think this behavior is right for protecting the gateway service, and my question is: the only way  to delay Ocelot's request timeout is setting the "QoSOptions" section -> "TimeoutValue"? I haven't set this section yet, because I worry about whether the two "Timeout" settings will work correctly between HttpClient's timeout and Polly's timeout. 

P.S: the slow service which likes a cow is a legacy service and maintains by another team. we could not improve the performance. >_<

so is my fear superfluous about two Timeout settings? 

thanks.

**Comment by TomPallister** [comment]
@BowAngel thanks for your interest in the project :)

This is a really good question! I don't know how this works. I will look into it and get back to you ASAP. 

Don't worry about your slow service :) I have been doing this job long enough to know we all have to deal with legacy :) I make most of it hehehe

**Comment by TomPallister** [comment]
@BowAngel so it turns out there was a difference in the timeouts. We have the normal HttpClient timeout which is always active, and defaults to 90 seconds (from my investigations). We also have the QoS stuff that is really just a Polly policy attached to a DelegatingHandler. 

I changed Ocelot so that the HttpClient would also respect QoSOptions.TimeoutValue. You can now safely use this to say a ReRoute can have a longer timeout. The value is set in milliseconds. 

I will release this in the NuGet package ASAP.

**Comment by TomPallister** [comment]
@BowAngel HttpClient was not using QoS TimeoutVale as its timeout setting so this would not have worked for you in previous version.

I have just released version 5.5.3 that has a fix for this issue so if you get that it should work. I have updated the docs [here](http://ocelot.readthedocs.io/en/latest/features/qualityofservice.html) this should explain how it all works!

**Comment by emiliovmq** [comment]
Hi there, I have one question regarding the HttpTimeOut (default 90 secs). Currently, we have Ocelot (13.4.1) running in production, it is not using QoS (therefore Ocelot.Provider.Polly was not included in the release). Now we are seeing some weird error messages in the logs "_System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request._". For all cases, the downstream call referred to a new service and took a long time to complete - which is what we were expecting -, but Ocelot did not wait for that response and threw the exceptions. I'm suspecting this is due to the default 90 secs for timeout, is there any way to set up a value greater than the default one in the configuration either globally or by route?

**Comment by culaja** [comment]
@emiliovmq Have you found the solution since I also have the same problem?
We get Pipe broken exception after 90 sec.

**Comment by xianrui69** [comment]
> @emiliovmq你找到解决方案了吗？我也有同样的问题。 90秒后出现管道破裂异常。

me too

**Comment by xianrui69** [comment]
me too

**Comment by xianrui69** [comment]
> @emiliovmq你找到解决方案了吗？我也有同样的问题。 90秒后出现管道破裂异常。

https://github.com/ThreeMammals/Ocelot/issues/604#issuecomment-1617083585

**Comment by raman-m** [comment]
>@emiliovmq commented [on Jun 17, 2022](#issuecomment-1159140942)

You use outdated Ocelot release v13 in production!
What about upgrading your solution to v19 for .NET 7 ?

After that just specify this QoS config:
```json
"QoSOptions": {
    "ExceptionsAllowedBeforeBreaking": 1,
    "DurationOfBreak": 1000,
    "TimeoutValue": 90000
}
```
Pay attention: `"ExceptionsAllowedBeforeBreaking": 1`! **It should be greater then zero**, according to [Quality of Service](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html) docs!

---
But even valid and good configuration of QoS doesn't guarantee on 100% that you won't get exceptions in logs.
For example, default settings (no QoS config section at all) generates exception in 90 seconds if the downstream service is offline.
Here is the [last paragraph](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html):
```
If you do not add a QoS section QoS will not be used however Ocelot will default to a 90 second timeout 
on all downstream requests. If someone needs this to be configurable open an issue.
```
So, if no QoS, current default behavior is generating the exception above. I know, it is not informative and it looks like something is broken. Yes, your downstream service is totally offline. That's why I believe this exception must be generated.
The rest of the debates to find some more informative error message.
And, I would say that Ocelot core should indicates in some way that downservice is offline.
It is abnormal that your service is offline for more than 90 seconds.

I advice to review current implementation and deployment of your service to be sure the service is online always.
There are a lot of approaches to do that, for instance, Warm Up cloud feature, and Health Check cloud feature which guarantee that service is online and ready for servicing.

As soon as you make sure your service is online, there will be no QoS exceptions generated by Ocelot.

---
Finally,
If you still consider current QoS behavior is not efficient/solid then you could open new issue with your user case to fix.

**Comment by raman-m** [comment]
@culaja commented [on Mar 13, 2023](#issuecomment-1466002362)
> @emiliovmq Have you found the solution since I also have the same problem?
We get Pipe broken exception after 90 sec.

Let's find a solution together! 😉 
Read [my answer](#issuecomment-1618801529) for @emiliovmq first.
Your user case will be fixed, the probability is 99% 🤣 
If Not, open new bug-issue please! 

Main solution is making sure your down service is online. 😉
