### ISSUE TITLE
Implementation with HttpClientFactory in ASP.NET Core 2.1 

### ISSUE THREAD

**Issue by CESARDELATORRE** [ThreeMammals/Ocelot#356]
Hey Tom! - Are you planning to move to **HttpClientFactory** in **ASP.NET Core 2.1** when moving Ocelot to .NET Core 2.1 in the upcoming future? :)

See a summary from Glenn in my team:
https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-preview1-introducing-httpclient-factory/

### Update on Nov 29, 2023
- [IHttpClientFactory with .NET](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory)
- [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests)
- [Use IHttpClientFactory to implement resilient HTTP requests](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
- Bing.com: [Search for "IHttpClientFactory"](https://www.bing.com/search?q=IHttpClientFactory)

**Comment by TomPallister** [comment]
@CESARDELATORRE yes, the factory looks really good and I will be changing Ocelot to use it. I will keep this issue open.

**Comment by dbarkwell** [comment]
I was playing around with it. I got it working (some of the tests are failing though) but something tells me it can be implemented differently. @TomPallister I would like to know your thoughts: https://github.com/dbarkwell/Ocelot/tree/net-21

**Comment by TomPallister** [comment]
@dbarkwell sounds good! I will take a look ASAP. I'm super busy at the moment (started a new job which is taking a lot of time)!

**Comment by binarymash** [comment]
@TomPallister fyi AppVeyor doesn't yet support dotnet core 2.1. Their VS2017 preview image does have the RC, but another of my projects is failing with this after upgrading today because of the new Microsoft.AspNetCore.App package (which replaces Microsoft.AspNetCore.All) still looking for RC dependencies.

No big deal though cos AppVeyor say it should be up and running later this week. Gives you a bit more time to get your work done ;)

**Comment by TomPallister** [comment]
@binarymash thanks for the info chief! I don’t think I’m going to be on the bleeding edge like you!!!!

**Comment by TomPallister** [comment]
@dbarkwell finally had a chance to look at this, your code looks like a good start apart from changing Ocelot to target netcoreapp2.1, it supports netstandard so it can be used in classic .net projects. Unless something has changed that I have missed netcoreapp does not work in classic .net?

**Comment by stefankip** [comment]
Any updates regarding this?

**Comment by jmezach** [comment]
Is anyone working on this? This would be a really great addition to Ocelot and could help with performance as well. I don't think it's necessary to change the target framework to netcoreapp2.1, because the [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http/2.1.0) package seems to target netstandard2.0.

**Comment by geffzhang** [comment]
> Is anyone working on this? This would be a really great addition to Ocelot and could help with performance as well. I don't think it's necessary to change the target framework to netcoreapp2.1, because the [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http/2.1.0) package seems to target netstandard2.0.

This does help improve performance

**Comment by jmezach** [comment]
Wouldn't mind taking a stab at this, although I don't necessarily know where to get started. If someone can point me in the right direction that would be great. Otherwise I would have to find some time to dig into how things currently work to figure out how we can change that to incorporate the Http Client Factory.

**Comment by raman-m** [comment]
@CESARDELATORRE commented [on May 12, 2018](#issue-322468179):
> Hey Tom! - 

I'm Tom's representative! And Tom is not at home! 😉 

Thank you for pointing our attention to `HttpClientFactory` problem! 5 years ago! 🤯 
But we still don't use [IHttpClientFactory](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+IHttpClientFactory&type=code) interface in Ocelot in 2023... 😮 That's terrible.
I know, not using this interface is a significant impact on performance...
Going to include to the next upcoming release...
Hope we will be able to add `IHttpClientFactory` interface in a simple way.

**Comment by raman-m** [comment]
@ggnaegi Seems we need to discuss the issue a little bit here...
