### ISSUE TITLE
Allow users to set useproxy on httpclient

### ISSUE THREAD

**Issue by fablacky** [ThreeMammals/Ocelot#390]
Although my gateway is quite fast on development, once it gets published, every request takes about 2-3 seconds longer to complete no matter what. I did some digging and apparently it's a very well known issue involving the HttpClient. 
The following url helped me a lot:
[https://github.com/dotnet/corefx/issues/6180](url) 
I edited your HttpClientBuilder set the UseProxy propert to false when instantiating the HttpClientHandler.
![image](https://user-images.githubusercontent.com/17791461/41103735-234185ac-6a6a-11e8-9152-57b80c8c9bd1.png)

As a result all my requests are as fast as on develop environment. Do you think this qualifies as an added entry in the configuration file? 
Thank you so much for your attention and support.

**Comment by TomPallister** [comment]
@fablacky interesting that no one else has run into this problem! I was not aware of it. Is this not because there is some kind network configuration issue as per the last comment in the issue you have linked to this?

Regardless it is probably a valuable option to allow users to configure! I would happily accept a PR for this if you feel like taking the issue on.

**Comment by TomPallister** [comment]
Released in 7.0.5
