### ISSUE TITLE
Should I be able to reRoute to a rest controller rather than a service?

### ISSUE THREAD

**Issue by wayne-o** [ThreeMammals/Ocelot#431]
## Expected Behavior / New Feature

When I configure ocelot to resolve something like 

```
"DownstreamPathTemplate": "/api/v1/permissions/{everything}"
"DownstreamHostAndPorts": [
            {
                "Host": "service.permissions",
                "Port": 80,
            }
 ],
"UpstreamPathTemplate": "/api/v1/permissions/{everything}"
```

It should be able to map to http://service.permissions/api/v1/permissions/

## Actual Behavior / Motivation for New Feautre

404

Note: 
 - when I navigate to  http://service.permissions/api/v1/permissions/ it works
 - when using this config it works (Ocelot is able to re-route my request correctly):
```
"DownstreamPathTemplate": "/api/v1/{everything}"
"DownstreamHostAndPorts": [
            {
                "Host": "service.permissions",
                "Port": 80,
            }
 ],
"UpstreamPathTemplate": "/api/v1/{everything}"
```
The reason this is an issue for me is that I have a service with 3 controllers:

-  1 of the controllers requires auth on all POST/GET/DELETE etc 
- 1 of the controllers has mixed: no auth on GET, auth on POST/DELETE/PUT
- 1 of the controllers has no auth at all

So I would like to be able toc onfigure re-routes on a per controller bases - my controllers are restful so GET /permissions/ maps to PermissionsController.Get - if that matters

I wonder if the RegEx requires a trailing `/`? as that would not be present on a query like:

 http://service.permissions/api/v1/permissions?filter[name]=test

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@wayne-o  The routes `/api/v1/permissions/{everything}` and `/api/v1/permissions/` are different which is why you get a 404. A user might want one behaviour for /permissions/ and a different behaviour for /permissions/xxx which is why Ocelot works like this.

If you set up a ReRoute with `/api/v1/permissions/` then all the requests will be routed to your controller. You can then separate out different functionality for HTTP verbs using the UpstreamHttpMethod property e.g.

```json
"UpstreamHttpMethod": [
              "Get"
          ],
```

Hope that helps! Let me know if you are still struggling.
