### ISSUE TITLE
Using Admin Api update configuration successfully,but the json file not changed.when I restart the Ocelot service,the configuration was restored.

### ISSUE THREAD

**Issue by xiaoqiuGit** [ThreeMammals/Ocelot#463]
## Expected Behavior / New Feature
Using Admin Api update configuration successfully,but the json file not changed.when I restart the Ocelot service,the configuration was restored.
`        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>().UseUrls("http://127.0.0.1:8000")
          .ConfigureAppConfiguration((hostingContext, builder) =>
          {
              builder.AddJsonFile("Ocelot.json", false, true);
          });`
Ocelot.json file not changed.So I restart the service,the configuration was restored.

## Actual Behavior / Motivation for New Feautre
when the configuration updated by admin api successfully,the configuration file should be updated synchronously?
Is there a way to solve this problem?

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@xiaoqiuGit thanks for your interest in the project. 

There are a few similar issues already open. The way I handle the config just isn't very good. 

I think what is happening...when you edit the config using the admin api it actually updates ocelot.{environment}.json on the disk. When you then restart ocelot it reads the configuration from ocelot.json because you do `AddJsonFile("Ocelot.json")` and that will overwrite whatever is in ocelot.{environment}.json.

This is a bug and I will fix it ASAP.

**Comment by TomPallister** [comment]
if You manually change the file while Ocelot is running it will not pick up the updates. The reason for this is Ocelot translates the file into an internal configuration. It is a bit messy and I know it needs to be improved :(

**Comment by TomPallister** [comment]
This is fixed in version 8.0.3, please check it out!
