### ISSUE TITLE
Recommended approach to add dynamic header

### ISSUE THREAD

**Issue by Savij** [ThreeMammals/Ocelot#468]
Hi,

Before I ask my question, here is my topology (by public/private I mean which endpoints can be seen by other endpoints):
**[Setup]**
- public react client
- public okta OIDC (oAuth2)
- public/private - Ocelot can be hit by public and private endpoints
- private micro services (only Ocelot has access)

I am using this on existing software that has it's own home grown authorization role system that gets tied to an application based userId.

**[Flow]**
Once a user authenticates via Okta,I have a token that contains their email address. I can use this email address to lookup the UserId for that application. I want to send that UserId in a header when I call the microservices. Since users can't get to the microservice and the email is read from the token, it should be safe to do. I can cache the id values at the Ocelot layer.

**[Question]**
My question is where should I be looking up the UserId (from the email address) in Ocelot? I almost need a hook right before I call the downstream service where I can check the cache and/or get the UserId and add it to a header. I just don't know how (or when) Ocelot would want me to do the lookup and header add.

Thanks for any help!
-Jeff

**Comment by TomPallister** [comment]
@Savij sorry for the slow response, I have been away for a few days 😄 

So I think you could do this using a injected middleware docs are [here](http://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html) the middleware you want to inject is PreQueryStringBuilderMiddleware. Before calling next in the overriding middleware you can access context.DownstreamRequest.Headers and add whatever header you want and Ocelot will send this to the downstream service. The negative to doing it this way is you cannot do dependency injection nicely because you have to pass the function that you assign to PreQueryStringBuilderMiddleware manually, you can use a factory / function to make it a bit better if you want transient services in it. Btw the naming of the middleware injection is terrible. I almost want to get rid of this feature but leaving it for now!

Alternatively you can use a DelegatingHandler docs [here](http://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) this allows you to manipulate the .net HttpRequestMessage object that Ocelot uses to talk to the downstream service. These can use normal dependency injection in .net so it might be a bit nicer. I think this would be the better way to do it.

Let me know if this works for you and if you run into any problems!

**Comment by Savij** [comment]
No worries, I was actually away for the week so it works out. I think the second solution sounds better. I can hook the DelegatingHandler and maybe setup a redis cache with the userId's. Might be a good place to also cache the user roles.

**Comment by TomPallister** [comment]
@Savij awesome, let me know if you have any problems!

**Comment by svipandi** [comment]
@TomPallister 

I need to call auth server from my api gateway. Auth server return the token. I need to cache the token in the gateway itself. next subsequent request i need to attach the token and forward the request to the corresponding micro service. How we can implement in the gateway

**Comment by TomPallister** [comment]
@svipandi Why do you need to cache the token? I think you probably just need to implement an authentication handler that does all your logic and then use this in Ocelot...should work! But I don't really know what your scenario is.

**Comment by govardhankumark** [comment]
> @Savij sorry for the slow response, I have been away for a few days 😄
> 
> So I think you could do this using a injected middleware docs are [here](http://ocelot.readthedocs.io/en/latest/features/middlewareinjection.html) the middleware you want to inject is PreQueryStringBuilderMiddleware. Before calling next in the overriding middleware you can access context.DownstreamRequest.Headers and add whatever header you want and Ocelot will send this to the downstream service. The negative to doing it this way is you cannot do dependency injection nicely because you have to pass the function that you assign to PreQueryStringBuilderMiddleware manually, you can use a factory / function to make it a bit better if you want transient services in it. Btw the naming of the middleware injection is terrible. I almost want to get rid of this feature but leaving it for now!
> 
> Alternatively you can use a DelegatingHandler docs [here](http://ocelot.readthedocs.io/en/latest/features/delegatinghandlers.html) this allows you to manipulate the .net HttpRequestMessage object that Ocelot uses to talk to the downstream service. These can use normal dependency injection in .net so it might be a bit nicer. I think this would be the better way to do it.
> 
> Let me know if this works for you and if you run into any problems!

This was helpful. thanks
