### ISSUE TITLE
Access to the path Denied

### ISSUE THREAD

**Issue by moyotalero** [ThreeMammals/Ocelot#484]
In production I have the following error, the file exists and although it is not resolved

![sin titulo](https://user-images.githubusercontent.com/12578428/43032280-c48780b2-8c78-11e8-8838-5b5acc1a1f7e.png)

.Net core 2.1

**Comment by TomPallister** [comment]
@moyotalero this is most likely because Ocelot does not have permission to write to disk.

There is already an issue open https://github.com/ThreeMammals/Ocelot/issues/373 to not write to disk unless using the admin API.

Short term fix is probably to give Ocelot permission to write to that file on disk (nothing else)

**Comment by TomPallister** [comment]
Closing as duplicate, reopen if this is not the case!
