### ISSUE TITLE
Intention to Contribute for Adding Support for Redis

### ISSUE THREAD

**Issue by allanchua101** [ThreeMammals/Ocelot#619]
## Inquiry and not a bug at all
Hi Guys,

Can I politely ask how can I contribute by adding support for Redis-based rate limiting?

Would love to help out this wonderful project!

Regards,
Allan

**Comment by TomPallister** [comment]
@allanchua101 first thanks for your interest in the project. It is really appreciated. 

The first thing we were thinking of doing with rate limiting is improving our basic implementation....this is not really documented yet but the issue is #553. The general idea was to move our rate limiting to a bucket algorithm.

After that the idea is it will be much easier to implement different providers because we will have a better abstraction.

I don't really know the rate limiting code that well, to just hack it out and get it working with what Ocelot already has might just be a case of implementing IRateLimitCounterHandler.cs for Redis. You are welcome to give it a go. 

All the Ocelot services are registered with TryAddSingleton so you can easily override this with your rate limit provider.

You can do it in the Ocelot project (make things simple) but I would break this out into another package like Ocelot.Provider.Redis eventually so Ocelot doesn't have a dependency on Redis. In theory you don't even need to touch Ocelot to get it working due to TryAddSingleton but I don't know 100%.

Hope that makes sense and provides some guidance.
