### ISSUE TITLE
Preflight requests are being handled by the Authentication Pipeline

### ISSUE THREAD

**Issue by arielmoraes** [ThreeMammals/Ocelot#633]
According to the W3 spec, prefights requests should not send Authentication headers, but if Authentication is added to a ReRoute configuration with an OPTIONS mapping the request fails with a 401 response.

![image](https://user-images.githubusercontent.com/6741634/45938694-b1006380-bfa2-11e8-9a34-3f30ecb0b5a7.png)

I tried to create another ReRoute config with the same UpstreamRoute but with only the OPTIONS method but Ocelot does not like it.

**Comment by TomPallister** [comment]
@arielmoraes Thanks for this....all this make sense to me! I guess it hasn't come up before because people normally use the asp.net cors middleware before Ocelot so it never get's down the Ocelot pipeline...not 100% sure though. 

I really appreciate your interest in Ocelot and the fact you have submitted this PR :) thank you!!!!!!!! I will get it merged an released in the NuGet package ASAP.

**Comment by arielmoraes** [comment]
@TomPallister No problem, I tried to put the CORS middleware before ocelot and the problem persists. Waiting for the stable versions to update Ocelot.

**Comment by TomPallister** [comment]
Released in 12.0.1, should be on NuGet soon :)
