### ISSUE TITLE
store configuration in consul  problem on v12.0.0

### ISSUE THREAD

**Issue by q315523275** [ThreeMammals/Ocelot#641]
## Expected Behavior / New Feature
hi

When the configuration is stored in consul, restarting the application causes local ocelot. json information to be synchronized to consul, resulting in loss of consul configuration data;

I find that every restart application is executed.

`if(AdministrationApiInUse(adminPath))`
`{`
    `   var fileConfigSetter = builder.ApplicationServices.GetService<IFileConfigurationSetter>();`
    `   await SetFileConfig(fileConfigSetter, fileConfig);`
`}`
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:v12.0.0
  - Platform:
  - Subsystem:

**Comment by TomPallister** [comment]
@q315523275 mmmmm I will check this out ASAP, I thought I fixed this already.

**Comment by TomPallister** [comment]
@q315523275 Ive had a chance to look at this issue, it looks like expected behaviour. If you are using the administration API when Ocelot starts up it writes to ocelot.json and ocelot.{env}.json because users expect both of these configs to be in sync.

If you are using consul instead of using DiskFileConfigurationRepository to do the save it uses the Consul version and hence it saves to your consul instance.

The fix for this is say if using consul to store ocelot configuration don't save the config when starting Ocelot. This would mean exposing some kind of delegate from Ocelot.Provider.Consul package.

For now I would suggest dont use the administration api when using Consul. You shouldnt need both.

**Comment by q315523275** [comment]
@TomPallister Thank you very much for your reply. I will use API management in another way.
