### ISSUE TITLE
Ocelot crashes if there are same-named Catch-Alls e.g. `foo/{bar}/{bar}`

### ISSUE THREAD

**Issue by ChrisSwinchatt** [ThreeMammals/Ocelot#683]
## Expected Behavior

An informative exception which tells you you can't reuse catch-all names within a path.

## Actual Behavior

This exception, which doesn't tell you what is wrong and looks like a bug in Ocelot:

```
[15:05:22 FTL] Application startup exception
System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at Ocelot.Configuration.Creator.UpstreamTemplatePatternCreator.Create(IReRoute reRoute)
   at Ocelot.Configuration.Creator.ReRoutesCreator.SetUpDownstreamReRoute(FileReRoute fileReRoute, FileGlobalConfiguration globalConfiguration)
   at Ocelot.Configuration.Creator.ReRoutesCreator.<>c__DisplayClass15_0.<Create>b__0(FileReRoute reRoute)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ocelot.Configuration.Creator.FileInternalConfigurationCreator.Create(FileConfiguration fileConfiguration)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.CreateConfiguration(IApplicationBuilder builder)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder, OcelotPipelineConfiguration pipelineConfiguration)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder)
```

## Steps to Reproduce the Problem

  1. Create an ocelot.json which contains the following re-route:

```json
        {
            "DownstreamPathTemplate": "/bar/{everything}/{everything}",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "foo",
                    "Port": 80
                }
            ],
            "UpstreamPathTemplate": "/foo/bar/{everything}/{everything}",
            "UpstreamHttpMethod": [
                "Get"
            ],
            "Priority": 0
        }
```

  1. Tell Ocelot to load it
  1. Get the above exception

## Specifications

  - Version: 12.0.1
  - Platform: ASP.Net Core 2.1
  - Subsystem:

**Comment by raman-m** [comment]
@AlyHKafoury Your next coding challenge? 😉
It is related to **CatchAll** and Placeholders.
I guess and I hope fixing not required but tests should be added.

**Comment by AlyHKafoury** [comment]
@raman-m please assign to me

**Comment by raman-m** [comment]
@AlyHKafoury You're [assigned](https://github.com/ThreeMammals/Ocelot/issues/683#event-11485301195)!

**Comment by AlyHKafoury** [comment]
@raman-m I working on the unit tests

**Comment by raman-m** [comment]
@AlyHKafoury 
Because you're working on very similar from #748 & #1911 then you need to create feature branch from [AlyHKafoury:Fix-748](https://github.com/AlyHKafoury/Ocelot/tree/Fix-748), otherwise you'll get duplicates.
So, the right thing is branching from [AlyHKafoury:Fix-748](https://github.com/AlyHKafoury/Ocelot/tree/Fix-748) ❕

**Comment by AlyHKafoury** [comment]
@raman-m I will rebase to develop now and continue on this

**Comment by raman-m** [comment]
> @raman-m I will rebase to develop now and continue on this

@AlyHKafoury Yes, rebase on **develop** please and continue working... Thanks!

**Comment by raman-m** [comment]
> @ChrisSwinchatt commented [on Nov 12, 2018](https://github.com/ThreeMammals/Ocelot/issues/683#issue-379819842)

Hello, Mr. Swinchatt!
Thanks for reporting this funny bug! 😄 How did you test Ocelot in this user scenario, and realize to define this invalid duplicated placeholders? Toy have some QA talent! 😉 

Yeap, we've missed the thing, and in my opinion, the valid template definition should have all placeholders with different names, and each upstream placeholder should be presented in downstream template too.
**Otherwise**, route validator should
- generate `Critical` error, and Ocelot will not start
- ignore this route, write `Error` event to the log and start Ocelot without this route in router mappings.

Make sense? Which design suits your usage best?
Do you use Ocelot in your current projects?

@AlyHKafoury  FYI

**Comment by ChrisSwinchatt** [comment]
Hello @raman-m,

I'm no longer working with Ocelot but IIRC I was writing code to generate an Ocelot config by traversing Swagger documents and it had a bug that resulted in outputting duplicate placeholders. So you could say that my bug found your bug. To your question, I would probably go the route of crashing early, but I leave it to you.

Thanks.

**Comment by raman-m** [comment]
@ChrisSwinchatt Thanks for your reply!

>I was writing code to generate an Ocelot config by **traversing Swagger documents** and...

Since you are a big fan of Swagger, here is some useful information for you :point_right: 
- PR #1429. As a Ocelot core team, we want to add Swagger support this year. The author developed just amazing library, which will be incorporated to Ocelot soon, this year, not planned yet... but we will try to start the integration as soon as possible, giving it high priority.
- Here is [MMLib.SwaggerForOcelot](https://github.com/Burgyn/MMLib.SwaggerForOcelot) project by @Burgyn. This is perfect tool which will be very useful for you. :yum: 

Do not you mind, if we will create separate [discussion](https://github.com/ThreeMammals/Ocelot/discussions) where we can start brainstorming an integration and Swagger support, and I will invite you also to the thread?

------
> To your question, I would probably go **the route of crashing early**, but I leave it to you.

:ok: Today I realized that ignoring the route will not be good. To crash early we can generate early validation `Critical` error, and moreover, if a request comes and matched the route then additionally write `Error` event to the log for each request. Crashing entire app won't be good, by exception throwing having it as unhandled one. So, we can generate exception, but we have to catch it in Error Mapper and write events into the log.

@AlyHKafoury  FYI.
Take into account this new design & requirements, please! :point_up:

**Comment by AlyHKafoury** [comment]
@raman-m Continuing on it

**Comment by AlyHKafoury** [comment]
@raman-m  So, we are gonna throw a Critical error in validation, and then start the application normally then throw an error when a route matching this route is called ? and we will not crash the application ?

**Comment by raman-m** [comment]
Aly, I thought you're on vacation. :) Welcome back! :wink:

Regarding validation...
You need a small research of validation logic.
Something related to uniqueness of placeholders. If no validator, try to find another validators of uniqueness of route properties. And seems we need to do the same.
Also, figure out, is it possible to write into the log by validation logic. I hope, it is possible outside of validation function. 
As far as I know, if validation function returns `false` then Ocelot crashes and the app won't start at all.
What I'm trying to say, that there is restriction here by validation design. Possibly we have to crash app early, because validation function will return `false`. In this case we have a record in the log anyway by already implemented design.

The 2nd requirement to write extra record makes sense only if Ocelot won't crash.
Probably, we can skip the 2nd requirement.

**Comment by raman-m** [comment]
>@ChrisSwinchatt commented [on Jan 20](https://github.com/ThreeMammals/Ocelot/issues/683#issuecomment-1901115708)

Hi Chris!
#### FYI: Bug fixed today!
But we used not "an informative exception" solution and chose another solution based on Ocelot configuration validator adding more [validation rules](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+IsPlaceholderNotDuplicatedIn+IsUpstreamPlaceholderDefinedInDownstream+IsDownstreamPlaceholderDefinedInUpstream&type=code) for route templates. With this bug fix Ocelot won't start because of validation errors in the log. And user must correct invalid routes with bad templates.

This patch will be released soon...
