### ISSUE TITLE
Documentation for .NET Core 2.1 Authentication.

### ISSUE THREAD

**Issue by bvkeersop** [ThreeMammals/Ocelot#694]
Hey all,

First of all, thanks for making this project! I'm sure all of you are busy. 
This isn't a huge deal but it was a bit unclear for me. I followed the start up at for .NET Core 2.1: https://ocelot.readthedocs.io/en/latest/introduction/gettingstarted.html

When I tried to implement authentication, I did it in my startup file like in the documentation:
https://ocelot.readthedocs.io/en/latest/features/authentication.html

This however does not work, you need to implement it in the Program.Main in the WebhostBuilder.ConfigureServices. I'm sure most people figure it out before I did. But the documentation threw me off a bit here.

Have a nice day!

**Comment by thiagoloureiro** [comment]
@bvkeersop  I have implemented authentication with JWT with .NET Core 2.1, I can help you with that and do a PR with this :)
In my repo I have it running, please check if is that you need.

https://github.com/thiagoloureiro/APIGatewayOcelot

**Comment by margaale** [comment]
@bvkeersop I have something like          
``` 
return WebHost
                .CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((builderContext, config) =>
                {
                    config.AddJsonFile($"ocelot.{builderContext.HostingEnvironment.EnvironmentName}.json", false, true);
                })
                .UseStartup<Startup>();
```
That way you can setup your services in the Startup class...

**Comment by raman-m** [comment]
@bvkeersop commented [on Nov 20, 2018](https://github.com/ThreeMammals/Ocelot/issues/694#issue-382686638)

> I followed the start up at for **.NET Core 2.1**:

2.1 is out of support by Microsoft .NET team!!!
Moreover, since November'23 we support .NET 6+ only as current versions in support by Microsoft.
Please,  upgrade to the latest version 22.0 with .NET 8

Regarding instructions in docs... It varies from version to version. We are interested to have valid instructions for .NET 6+ only.

**Comment by raman-m** [comment]
Not accepted for development!
Outdated because of legacy version 2.1
