### ISSUE TITLE
Pass on QueryString from Upstream to Downstream

### ISSUE THREAD

**Issue by stephanonline** [ThreeMammals/Ocelot#699]
## Expected Behavior / New Feature
I want to forward the queryString parameters passed on the original request to the downstream.

## Actual Behavior / Motivation for New Feature
When using the following configuration:
 ```
{
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/messaging/{url}",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ]
    }
```
I want to pass on optional queryStrings as well. 
So when navigating to:
http://localhost:6992/messaging/api/v1/messages?contractId=86  
I want it to be passed on like: 
http://localhost:5001/api/v1/messages?contractId=86
But for this scenario as well:
http://localhost:6992/messaging/api/v1/messages
I want it to be passed on like: 
http://localhost:5001/api/v1/messages

## Specifications

  - Version: 12.0.1
  - Platform: win, net462
  - Subsystem:

**Comment by wast** [comment]
Isn't this already working? https://ocelot.readthedocs.io/en/latest/features/routing.html#routing

![image](https://user-images.githubusercontent.com/9076227/78176616-10271a00-745d-11ea-9e11-f5e2321b9546.png)

**Comment by raman-m** [comment]
Hi @stephanonline !
The [Routing](https://ocelot.readthedocs.io/en/latest/features/routing.html) feature was implemented long years ago. So, [Placeholders](https://ocelot.readthedocs.io/en/latest/features/routing.html#placeholders) work fine.

------
```json
{
     "DownstreamPathTemplate": "/{url}",
     "UpstreamPathTemplate": "/messaging/{url}",
}
```
Your route is absolutely valid, because [This will forward any path + query string combinations to the downstream service after the path](https://ocelot.readthedocs.io/en/latest/features/routing.html#placeholders:~:text=This%20will%20forward%20any%20path%20%2B%20query%20string%20combinations%20to%20the%20downstream%20service%20after%20the%20path)
Are you still with Ocelot?

**Comment by raman-m** [comment]
Not an issue! Question has been [answered](https://github.com/ThreeMammals/Ocelot/issues/699#issuecomment-1880066908).
