### ISSUE TITLE
Cache keys should take added query params into account

### ISSUE THREAD

**Issue by dorgold** [ThreeMammals/Ocelot#707]
## Expected Behavior
Cache entries should take new query params into account (when creating cache keys)

## Actual Behavior
Currently the output cache is using the following key:
`var downstreamUrlKey = $"{context.DownstreamRequest.Method}-{context.DownstreamRequest.OriginalString}";` [(Link to line)](https://github.com/ThreeMammals/Ocelot/blob/41d4f9c6dfa3069dc9035e2e82d0c46f7f08cf56/src/Ocelot/Cache/Middleware/OutputCacheMiddleware.cs#L33)

Which takes only the original URL into account, i would suggest using `context.DownstreamRequest.ToUri()` instead of `context.DownstreamRequest.OriginalString`, so that the cache will take into account query params which were added during the request pprocessing in other middlewares.

Will you accept such a PR?

**Comment by philproctor** [comment]
I would approve this, seems to be an oversight to not cache the query params with the key

**Comment by wast** [comment]
I can confirm that these are successfully cached.

Config: 
```
    {
      "DownstreamPathTemplate": "/api/v1/dummydummy?productId={id}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "10.243.157.76",
          "Port": 8080
        }
      ],
      "UpstreamPathTemplate": "/dummy-endpoint?id={id}",
      "UpstreamHttpMethod": [ "Get" ],
      "FileCacheOptions": {
        "TtlSeconds": 3600,
        "Region": "dummy-regiona"
      },
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "ApiSecurity",
        "AllowedScopes": []
      }
    },
```

```cs
     services.AddOcelot()
                .AddCacheManager(x =>
                {
                    x.WithDictionaryHandle();
                });
```

**Comment by raman-m** [comment]
> @wast commented [on Apr 1, 2020](https://github.com/ThreeMammals/Ocelot/issues/707#issuecomment-607465346)

Yes, URL with query strings will be cached like that. But you've [added another cache](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot.Cache.CacheManager/OcelotBuilderExtensions.cs#L12) 🤣 

But the problem in the [OutputCacheMiddleware code](https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/Cache/Middleware/OutputCacheMiddleware.cs#L35) still remains.
If you not call `AddCacheManager` then `OutputCacheMiddleware` will cache and the problem persists because `OutputCacheMiddleware` is [embedded into the pipeline](https://github.com/search?q=repo%3AThreeMammals%2FOcelot%20UseOutputCacheMiddleware&type=code).

**Comment by raman-m** [comment]
## Outdated issue
@dorgold 
> Will you accept such a PR?

Yes, we will be glad to review. But pay attention a lot of things have changed.
We cache by body for example: [EnableContentHashing option](https://ocelot.readthedocs.io/en/latest/features/caching.html#enablecontenthashing-option)

### You have the right to reopen this issue in the future if you come with a PR ready
