### ISSUE TITLE
Placeholder in DownstreamHostAndPorts

### ISSUE THREAD

**Issue by ifyonyekpe** [ThreeMammals/Ocelot#726]
Is it possible to achieve this with Ocelot?

Environment Variables
`ApiName` : `account`
`EnvironmentName` : `dev`

```json
{
    "Routes": [
        {
            "DownstreamPathTemplate": "/{everything}",
            "DownstreamScheme": "http",
            "UpstreamPathTemplate": "/{everything}",
            "UpstreamHttpMethod": ["Get", "Put", "Delete", "Post"],
            "DownstreamHostAndPorts": [{
                    "Host": "api.{ApiName}.{EnvironmentName}",
                    "Port": 80
                }
            ]
        }
    ],
    "GlobalConfiguration": {
        "BaseUrl": "https://localhost:8080"
    }
}
```

**Comment by jeffersantoss** [comment]
Can this be achieved on the current Ocelot version?

**Comment by gao-artur** [comment]
You can easily add it yourself
https://stackoverflow.com/a/63601248/2557855

**Comment by raman-m** [comment]
@ifyonyekpe  Hi John!
Are you still interested in discussions after 5 years of Ocelot usage? 😉 

My answer: **"It is impossible**" 
Your request looks like a life hack for your user scenario. And you are ignoring a lot of useful and ready features of Ocelot, see below 👇 

---
- To setup multiple environments using **ocelot.json** config file,  you should use: [Multiple environments](https://ocelot.readthedocs.io/en/latest/features/configuration.html#multiple-environments). This is special [Configuration](https://ocelot.readthedocs.io/en/latest/features/configuration.html) feature for multiple environments.
- To setup one static `everything`-route, you should use [Catch All](https://ocelot.readthedocs.io/en/latest/features/routing.html#catch-all) route mode of [Routing](https://ocelot.readthedocs.io/en/latest/features/routing.html) feature.
- To setup one static `everything`-route and replace the host/port, you should integrate Ocelot to a [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) provider.
- To setup many dynamic `everything`-routes and having the host being replaced, you should use [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#dynamic-routing) special Ocelot core mode of [Service Discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html) feature.

Hope it will help you!

---
I'm going to close this issue because required Ocelot behavior can be designed, implemented and configured by current Ocelot features.

**Comment by raman-m** [comment]
@jeffersantoss commented [on Apr 27, 2023](#issuecomment-1526039232)
> Can this be achieved on the current Ocelot version?

Hi Jefferson!
Yes, it can!
See [my tips](#issuecomment-1614695810) above! ☝️

**Comment by raman-m** [comment]
The feature request is **not accepted**!
Reason: Very rare user case, can be covered by current functionality

Interested sides of this discussion could create PR(s) with ready solutions and link to this issue with reopening.
