### ISSUE TITLE
Developer Contribution Documentation

### ISSUE THREAD

**Issue by philproctor** [ThreeMammals/Ocelot#742]
## Expected Behavior / New Feature
Need to update documentation for contribution/development guidelines and criteria. Also need to add information on Linux builds.

## Actual Behavior / Motivation for New Feature
Existing documentation is pretty basic.

**Comment by postmeback** [comment]
Hi @philproctor , I would like to contribute over here. Requesting you to guide me.

**Comment by raman-m** [comment]
@philproctor 
Hi Phil !
I believe the [Documentation](https://ocelot.readthedocs.io/en/latest/index.html) is built and ready now, right?
I guess this task/issue can be closed because the documentation is already finished in 2023.
Could you confirm that your planned docs building is over now, after these 4 years?

**Comment by raman-m** [comment]
Current artifacts:
- The paragraph in [README.md](../blob/develop/README.md#contributing)
- The contributing template in [CONTRIBUTING.md](../blob/develop/.github/CONTRIBUTING.md)
- The folder with templates for developers to contribute: [.github](../tree/develop/.github)
- Linux builds are made by CircleCI pipelines:
  * The configs in folder: [.circleci](../tree/develop/.circleci)
  * CircleCI Project: [Ocelot](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot)
  * Building process is documented in the folder: [docs/building](../tree/develop/docs/building)

Taking into account all current artifacts above, I would say that Contribution and Builds docs are developed well, not bad definitely.
Having all these artifacts is sifficient to support the project. Sure, some typos in docs and broken links can be found. But they will be fixed while working on a concrete feature.

@philproctor  Phil,
I'm going to close the issue. This issue cannot be accepted because of very abstract description.
The issue description should be more concrete!
You are welcome to come back to this issue in future and open some PR(s) to review!
