### ISSUE TITLE
Bad error handling for IOException while reading incoming request body

### ISSUE THREAD

**Issue by davidni** [ThreeMammals/Ocelot#749]
## Expected Behavior

If an `IOException` happens while reading the incoming request body (in `RequestMapper.MapContent` [here](https://github.com/ThreeMammals/Ocelot/blob/02e5cea7b1bdd3d78cfe1a5bb688383f54a809fc/src/Ocelot/Request/Mapper/RequestMapper.cs#L24)), Ocelot fails the request with an `UnmappableRequestError` and status code 404.

404 is not appropriate, and the error logged by ocelot should be more specific than `UnmappableRequestError`. It just so happens that the exception happens while doing request mapping, but it's really an IO problem while reading the incoming request stream. Response status shouldn't be 404. In the case of too large request, 400 might be appropriate. In other cases, something in the 5xx range.

## Steps to Reproduce the Problem

This happens consistently, for example, for requests that are too large for the server (`HttpSys` throws an IOException if the Content-Length of the incoming request is larger than 30MB by default -- see: [AspNetCore source](https://github.com/aspnet/AspNetCore/blob/cd0eab88eaa230fa276c27ab5dc71ea267efe14f/src/Servers/HttpSys/src/RequestProcessing/RequestStream.cs#L435-L436)).

  1. Send a request to Ocelot, hosted on HttpSys, with Content-Length larger than 30,000,000.
  1. Boom!

Ocelot returns 404, and logs `UnmappableRequestError`.

## Specifications

  - Version: 12.0.1 (should also apply to 13.0.0 by code inspection)
  - Platform: Windows Server 2016 / .NET Framework 4.6.2

**Comment by daoye** [comment]
This behavior is confusing.

**Comment by Jalalx** [comment]
I think [413 Payload Too Large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413) is a better error code. What do you guys think?
@TomPallister

**Comment by ks1990cn** [comment]
Hi,

I created sample projects to debug and understand this flow. Here my branch were I tried making change https://github.com/ks1990cn/Ocelot/tree/ts/issue_729. 

1.) Used Ocelot Gateway & created downstream.
2.) tried uploading 10MB, 30MB (File type).

Observation:
There is already 413 error by asp .net when large entity is tried to sent through gateway. 

I wasn't able to replicate this. 

Why this issue is being reported for Ocelot? Infact we get this error by asp .net that gets executed even before it hits Ocelot middleware due to request validation.
Reason mentioned by asp .net is due to security:
<img width="521" alt="image" src="https://github.com/ThreeMammals/Ocelot/assets/29522704/7a09557f-d34c-493f-85cb-69791651980f">


@ggnaegi @philproctor @Jalalx @davidni

**Comment by raman-m** [comment]
> @Jalalx commented [on Nov 9, 2020](#issuecomment-723938073)

Agree on 413! This is the best status code to return in case of Content-Length problems with request.

**P.S.** Don't reference Tom in chats. He doesn't read Ocelot GitHub notifications since 2020... Only current maintainers read notifications, it's me and Raynald.

**Comment by raman-m** [comment]
@ks1990cn I would prefer to wait for a reply from issue raiser, because I need to understand his vision and idea of fixing this bug.
If he will be silent then he will be unassigned.

**Comment by ks1990cn** [comment]
> @ks1990cn I would prefer to wait for a reply from issue raiser, because I need to understand his vision and idea of fixing this bug. If he will be silent then he will be unassigned. Let's wait for a couple of weeks, up to one month...

Sure.

**Comment by raman-m** [comment]
Wow! [David Nissimoff](/davidni) is Principal Software Architect at Microsoft!!!
I'm definitely interested in his bug fixing! 🤣

**Comment by ks1990cn** [comment]
> Wow! [David Nissimoff](/davidni) is Principal Software Architect at Microsoft!!! I'm definitely interested in his bug fixing! 🤣

Yes.. I am interested too

**Comment by ks1990cn** [comment]
Please refer to dummy changes I made on `RequestMapper.cs` on my branch https://github.com/ks1990cn/Ocelot/tree/ts/issue_729.

@raman-m  I respect your statement & waiting for @davidni to come with his idea on this bug. I am just trying to understand flow and understand what I can do to fix this, if anything comes up. Meanwhile I come up with following question:-

On `RequestMapper.cs` of my branch, I have created another parameterized which gives different `MaximumRequestBodySize` on different host server `IIS, Http.Sys, kestrel`. Is there any generic way to figure out `MaximumRequestBodySize` irrespective of hosted server?

**Comment by raman-m** [comment]
@ks1990cn  OK, great! In my opinion we can wait for David's reply for a months, and years... But who knows...
If your solution is ready, you could open a PR to **develop** branch.
Also, pay attention to the fact, we have another PR #1724 which relates to `RequestMapper`!

**Comment by ks1990cn** [comment]
Sure, I am looking into it.. Just I am trying to figure out -

On which hosting server current application is hosted, because `MaximumRequestBodySize` gives 30MB in every hosted server - IIS, https.sys, kestrel & we can modify it too, but how to find which one we are using in current application.

Looking into aspnetcore application too, to understand how I can find this value.

**Comment by raman-m** [comment]
The bug has been [accepted](#event-10722540755) due to open PR #1749 
- #1749

**Comment by raman-m** [comment]
> ## Steps to Reproduce the Problem
> 
> This happens consistently, for example, for requests that are too large for the server (`HttpSys` throws an IOException if the Content-Length of the incoming request is larger than 30MB by default -- see: [AspNetCore source](https://github.com/aspnet/AspNetCore/blob/cd0eab88eaa230fa276c27ab5dc71ea267efe14f/src/Servers/HttpSys/src/RequestProcessing/RequestStream.cs#L435-L436)).
> 
>   1. Send a request to Ocelot, hosted on HttpSys, with Content-Length larger than 30,000,000.
>   1. Boom!
> 

We need to fix this issue for [HttpSys](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/HttpSys/README.md) only, right?
But Ocelot team is not responsible for third-party deployments and hosting, except Docker and Kestrel hosting, with limited support of IIS user cases.
It seems this is very rare user case. And, It will be not easy to fix that because HttpSys IIS environment must be deployed for testing...

@davidni FYI

**Comment by raman-m** [comment]
> @ggnaegi commented [on Oct 30](#issuecomment-1785356233)

Great! But with low priority... when you will have free time.
