### ISSUE TITLE
Public Ocelot for Testing Purposes

### ISSUE THREAD

**Issue by thiagoloureiro** [ThreeMammals/Ocelot#818]
## Expected Behavior / New Feature
We have a public / testing ocelot for testing on the develop branch / feature branches

## Actual Behavior / Motivation for New Feature
For testing purposes with current issues to replicate will be easier

## Steps to Reproduce the Problem

N/A

## Specifications

- Droplet on DigitalOcean with API Gateway and few Sample API's Published for specific scenarios, to be defined

- Samples will be published in the latest versions

- For Issues we need to figure out where we're going to store the repo, a CD/CI will be automatically created when we have changes and deploy automatically to the droplet/container

**Comment by raman-m** [comment]
@thiagoloureiro  Thiago,

I cannot get it! Is it a bug or feature?
Did you mean current release Docker container? But it has no routing configs.

And, why do you require public Ocelot instance? It is not secure to test in public environments.
I see that you want to improve testing for Ocelot...
Currently we have CircleCi CI-CD builds. These pipelines help a lot!

Regarding specific bugs of user scenarios...
Do you understand that user should prepare development environment to show the bug?
This environment can be just localhost environment with Docker Compose project in some Visual Studio solution.
This solution must be uploaded to GitHub for example. After that it will be possible to provide test running sessions.

Having a public Ocelot environment has no much sense because issue/bug reporter has to publish code (Ocelot fork code) after that reporter should run CI-build, for example by CircleCI, make a Docker container, create Docker container in some cloud, for example in Azure. And not only gateway Docker container: user scenario can require a lot of services to be deployed!!!

The second major issue with this public testing environment is hosting costs.
Creation of such testing environment will cost from 50 up to a number of hundreds of USD/GBP!
Will you pay for hosting of this testing environment?

---
@TomPallister  Tom.
What do you think? Your opinion?

**Comment by thiagoloureiro** [comment]
This is 4y old.. can close it
