### ISSUE TITLE
Cache keys should take added header params into account

### ISSUE THREAD

**Issue by nurhat** [ThreeMammals/Ocelot#862]
## Expected Behavior / New Feature
Upon configuration,  cache keys should be calculated using headers.  Especially for localization issues, an endpoint can output different results  upon the Content-Language header.

## Actual Behavior / Motivation for New Feature

  cache keys are calculated using http method & http request path

 
  1.Add Content-Language to header 
## Specifications

  - Version: 13.2.0
  - Platform: .Net Core
  - Subsystem:

**Comment by raman-m** [comment]
Hi @nurhat !
This is very specific and rare user scenario. We will not integrate it to Ocelot core services because of performance reasons.
But you can develop and show us your [sample](https://github.com/ThreeMammals/Ocelot/tree/develop/samples) with implemented scenario. I believe you can create a PR from [these changes](https://github.com/ThreeMammals/Ocelot/compare/develop...nurhat:Ocelot:develop) in your forked repo.

If you have an intention to contribute, then please, re-open this issue.

### P.S.
Please, pay your attention to this feature commit https://github.com/ThreeMammals/Ocelot/commit/ba641b245968294245d487a7c33d1bcc039f789c which uses Header approach too! It should solve your problem and it should be useful for your user scenario.
