### ISSUE TITLE
Support dynamic routing configuration in Service Fabric

### ISSUE THREAD

**Issue by RamjotSingh** [ThreeMammals/Ocelot#939]
## New Feature
Having to deploy Ocelot every time routing changes is tedious. Ocelot allows for modifying the routes using json reload but without deployment it is not really possible to do this either. This increases the cost of managing services in general. The target of this feature is to modify\extend Ocelot in a way that once deployed, ocelot can adapt to changes in services behind the scene.

## Motivation for New Feature
[Traefik supports something similar](https://docs.traefik.io/configuration/backends/servicefabric/) and that is the real motivation behind this feature. Today we are using Traefik but a few unrelated reasons are forcing us to move away from it.

**Comment by raman-m** [comment]
Hi Ramjot!
Are you still with Ocelot?

**Comment by RamjotSingh** [comment]
No, since this wasn't picked up and we absolutely needed dynamic discovery, we went with Traefik.

**Comment by raman-m** [comment]
Oops! @RamjotSingh

I didn't know you are an engineer at Microsoft 😄 I won't say how much I love Microsofting, but I do like pro contributors, and I definitely don't like the situation when such a pro dev like you has not received enough attention.

Since I am working on the mad release of [.NET 10](https://github.com/ThreeMammals/Ocelot/milestone/13), I have looked into the code, and the idea you expressed in #940 is getting me excited. Now that we have released version [24.1](https://github.com/ThreeMammals/Ocelot/releases/tag/24.1.0) and the overall situation with [Dynamic Routing](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html#sd-dynamic-routing) has improved, I believe it is time to reopen this feature proposal.

If you intend to contribute, I expect great adventures while developing this feature. Imagine having to refactor a number of core classes, plus it seems we would need a separate [Service Fabric provider](https://ocelot.readthedocs.io/en/latest/features/servicefabric.html) (currently it's built-in, but that may change), and we must write tons of tests. But I hope everything will be alright in the end, with a successful contribution and a great feature inside.

### My question is:
When you walk with your kids, what ice cream pack will you buy and eat, considering three products (not mammals) with the slogans "Ocelot Micro Soft" or "YARP Mini Hard" or "Traefik Pink Sparkles"? 😆

-------
### P.S. 

> No, since this wasn't picked up and we absolutely needed dynamic discovery, **we went with Traefik**.

Who's "we"? A team at Microsoft? LoL.
Don't say to your boss that your team chose Traefik and not the politically correct YARP. Otherwise, you'll be fired. It's a joke...

**Comment by RamjotSingh** [comment]
2 years later, yes we did indeed end up with YARP, not because its a Microsoft product but coz

- Traefik has pretty much dropped support for SF, since v2, we had to write the provider on top of the dynamic file configuration stack that Traefik exposes
- Ocelot didnt support dynamic routing configs so it was a non-starter for us
- We had new requirements come in which needed us to massively change how routing happens, particularly, dynamically route to external urls as well to build a cohesive cross region routing stack and since YARP allows this to be achieved through cluster manifest management we went with that


All of this being said, if this isnt super urgent for you, I can look into floating the PR. We have fair amount of experience now with dynamic route discovery in SF, so we (me and my team) can likely bring that to Ocelot. Reading the doc however, I found it interesting that the pathprefix is a requirement for dynamic routing it seems? As in /products/API1/ab and /products/API2/def cannot go to different services in the background. In my opinion this might be limiting (infact our current system would not have worked with such a limitation).

**Comment by raman-m** [comment]
Great! Thanks, Ramjot, for the quick reply.
I will dive deeper into this and leave a comment tomorrow, trying to understand what you meant.

But for now:
> Ocelot didn't support dynamic routing configs, so it was a non-starter for us.

What kind of configuration do you/your team need especially for dynamic routing with [Service Fabric](https://ocelot.readthedocs.io/en/latest/features/servicefabric.html)?

FYI, here are the key points (I hope you're already familiar with them):
- Ocelot dynamic routing paths must have the first segment of the path as the service name to resolve instances by the discovery provider — and this is a limitation.
- The second and subsequent path segments of a dynamic route can be treated as a normal upstream path (of static route), and much functionality is available, including SF [Placeholders](https://ocelot.readthedocs.io/en/latest/features/servicefabric.html#placeholders). Thus, you can assemble the downstream URL as you wish. More about placeholders &rarr; [Routing Placeholders](https://ocelot.readthedocs.io/en/latest/features/routing.html#placeholders)
- I'm not sure, but probably we need to extend the [Dynamic Route Schema](https://ocelot.readthedocs.io/en/latest/features/configuration.html#dynamic-route-schema). Please look at [the schema](https://ocelot.readthedocs.io/en/latest/features/configuration.html#dynamic-route-schema) first.

**Comment by raman-m** [comment]
> @RamjotSingh commits as contribution to YARP &rarr; [dotnet YARP Commits by RamjotSingh](https://github.com/dotnet/yarp/commits?author=RamjotSingh)

I don't see your commits to YARP repo. Did you use another GH account?

**Comment by RamjotSingh** [comment]
YARP isnt a true reverse proxy, just a library to build one. Since ours uses our team specific constructs, it is a wrapper around YARP and since it doesnt really make a ton of sense, it isnt commited back into repo.

Also that core SF integration code was stabilized around a month back (we are still fixing a few auxiliary bugs around error handling when services are down) we havent committed it back.  But even when we do it will have to be outside of YARP's core repo. Coz it wont make sense in core repo.

I did read and mention the limitations in the Ocelot dynamic config above, they sound a bit too limiting to me. Any particular reason? Every ReverseProxy I evaluated all of them ask for paths (regex of prefixes) and use those for determining the endpoint to call.

**Comment by raman-m** [comment]
@RamjotSingh [wrote](https://github.com/ThreeMammals/Ocelot/issues/939#issuecomment-4492867654)

>I did read and mention the limitations in the Ocelot dynamic config above, they sound a bit too limiting to me. Any particular reason? Every ReverseProxy I evaluated all of them ask for paths (regex of prefixes) and use those for determining the endpoint to call.

It is limited now, but the limitation can be eliminated for the Service Fabric provider if we starts development in the future.
**I will contact you and answer you later after the [.NET 10](https://github.com/ThreeMammals/Ocelot/milestone/13) release. I'm very busy, sorry...**

My opinion is that the SF provider must be updated, tested, and be functional and useful even for Azure environments, because SF is the historical No.1 service discovery at Microsoft and for overall .NET development. Thus, I hope we will build a professional and production-ready SF provider for Ocelot.

Be patient! See you...
❗Please share your LinkedIn profile so I can connect with you privately. We have a Slack channel, but I don't use Slack anymore since two team members left the Ocelot team (they stopped contributing).

**Comment by RamjotSingh** [comment]
https://www.linkedin.com/in/ramjot-singh/
